# Updated : 2025.06.26
# Version : 1.5.7
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

######################## YamBMS Local Packages Version #########################

# You need to copy the `packages` folder into the same folder as this YAML in order to compile it.
# Don't forget to configure your WiFi credentials in the secrets.yaml

################################################################################

# Don't forget to configure your WiFi credentials in the secrets.yaml
#
# If needed, configure a static IP here
# wifi:
#   manual_ip:
#     static_ip: 192.168.0.85
#     gateway: 192.168.0.1
#     subnet: 255.255.255.0
#     dns1: 8.8.8.8
#     dns2: 8.8.4.4

logger:
  level: INFO # VERBOSE / DEBUG / INFO / WARN

ota:
  platform: esphome

# Please use the native `api` component instead of the `mqtt` section.
# If you use Home Assistant, the native API is more lightweight.
# If there is no HA server connected to this API, the ESP32 reboots every 15 minutes to try to resolve the problem.
# The "reboot_timeout: 0s" option will keep your ESP32 up and running even if you lose connection to your HA server.
api:
  reboot_timeout: 0s

# If you don't want to use ESPHome's native API you can use MQTT instead.
# In this case don't forget to remove the 'api:' section.
# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

# Please note that enabling this component will take up a lot of memory and may decrease
# stability and be the cause of reboot depending on the capabilities of the board used.
# web_server:
#   port: 80
#   log: false
#   ota: false

# +--------------------------------------+
# | Global Settings                      |
# +--------------------------------------+
substitutions:
  # Name
  friendly_name : 'YamBMS' # Prefix added in front of the `entity display name`, also used to classify them.
  hostname: 'pvbrain2' # Name of your ESPHome node registered on the IP network (DNS name, must be unique) and prefix added in front of the `entity id`.
  name: '' # This name can be added as a second prefix, both for the `entity display name` and the `entity id`, you can leave it blank.
  # +--------------------------------------+
  # | YamBMS Settings                      |
  # +--------------------------------------+
  # Please read the cut-off charging logic README to understand how the YamBMS works
  yambms_id: 'yambms1'
  yambms_name: 'YamBMS 1'
  yambms_update_interval: '1s'
  # Input numbers can be displayed as a slider or an input box, options are 'slider' or 'box'.
  yambms_input_number_mode: 'slider'
  # Please check and fill in the options below correctly according to your battery chemistry and number of cells in series.
  # These parameters are important and used for charging logic.
  # Battery Chemistry
  yambms_battery_chemistry: '1' # 1-LFP | 2-Li-ion | 3-LTO
  # Number of cells in series
  yambms_cell_count: '16'
  # Bulk / Absorption Voltage : corresponds to the Bulk voltage that will be used to charge the battery. (LFP : 55.2V = 3.45V/Cell for 16S battery)
  yambms_bulk_v: '55.2'
  # Float Voltage : corresponds to the voltage at which the battery would be maintained at the end of charge. (LFP : 53.6V = 3.35V/Cell for 16S battery)
  yambms_float_v: '53.6'
  # Rebulk voltage, voltage from which a new Bulk charge can start. (LFP : 52.8V = 3.3V/Cell for 16S battery)
  yambms_rebulk_v: '52.8'
  # Maximum time in minutes that the cut-off step can last before charging is complete
  # If your cells are properly balanced this step ends at the fastest after the `cut-off timer`
  # This timer can be deactivated with a switch
  yambms_eoc_timer: '30'
  # Time in seconds during which the end of charge conditions must be respected (cut-off + cells not equalizing)
  yambms_cutoff_timer: '60'
  # +--------------------------------------+
  # | Shunt Settings                      |
  # +--------------------------------------+
  shunt_update_interval: '3s'  # frequency at which Shunt data is refreshed
  shunt_combine_interval: '1s' # frequency at which Shunt data is combined in YamBMS
  # +--------------------------------------+
  # | BMS Settings                         |
  # +--------------------------------------+
  bms_update_interval: '3s'    # frequency at which BMS data is refreshed, going below '3s' can cause problems
  bms_combine_interval: '1s'   # frequency at which BMS data is combined in YamBMS
  bms_cutoff_timer: '50s'      # time during which the end of charge conditions must be respected (cut-off + cells not equalizing)
  # +--------------------------------------+
  # | WK2168 UART expander                 |
  # +--------------------------------------+
  uart0_baudrate: '2400'    #WKS         {RJ45-UART0}
  uart1_baudrate: '38400'   #JSY193
  uart2_baudrate: '19200'   #SmartShunt
  uart3_baudrate: '9600'    #SRNE        {RJ45-UART3}
  uart4_baudrate: '115200'  #JK-BMS 1
  uart5_baudrate: '115200'  #JK-BMS 2
  uart6_baudrate: '115200'  #Pylontech
  uart7_baudrate: '9600'    #EPEVER      {RJ45-UART7}

# +--------------------------------------+
# | PVbrain2 packages                    |
# +--------------------------------------+
packages:

  device_board: !include packages/board/board_ESP32-S3_DevKitC-1_PVbrain2.yaml

  # BUS
  # bus_i2c0: !include pvbrain2/base/device_bus_i2c0.yaml # SX1509 and BME280/BMP280
  bus_spi1: !include pvbrain2/base/device_bus_spi1.yaml # MCP2515
  # bus_one_wire: !include pvbrain2/base/device_bus_one_wire.yaml # Dallas

  # Devices
  # device_uart_esp: !include pvbrain2/base/device_uart_esp.yaml
  device_wk2168_spi: !include pvbrain2/base/device_wk2168_spi.yaml
  # device_wk2168_i2c: !include pvbrain2/base/device_wk2168_i2c.yaml
  # device_sx1509: !include pvbrain2/base/device_sx1509.yaml
  device_canbus_node1: !include pvbrain2/base/device_canbus_esp32can.yaml # canbus_node1
  device_canbus_node2: !include pvbrain2/base/device_canbus_mcp2515.yaml  # canbus_node2

# +--------------------------------------+
# | YamBMS packages                      |
# +--------------------------------------+

# PLEASE READ : https://github.com/Sleeper85/esphome-yambms/blob/main/documents/README/YamBMS_main_YAML_HowTo.md

  ################ >>> CONFIG & CUSTOM LP <<< ################

  # Local Packages intended for creating custom codes
  # or sharing settings between several main.yaml

  # yambms_config: !include yambms_config.yaml
  # yambms_custom: !include yambms_custom.yaml

  # You don't have to import a shunt but you must import at least one BMS.

  # shunt1: !include
  #   file: packages/shunt/shunt_combine_Victron_SmartShunt_UART_expander.yaml # shunt_combine_Junctek_KHF_UART.yaml
  #   vars:
  #     shunt_id: '1' # must be a number
  #     shunt_name: 'Shunt 1'
  #     shunt_uart_id: 'uart_${uart_hub_bus}_2'

  bms1: !include
    file: packages/bms/bms_combine_JK_UART_4G-GPS_full.yaml
    vars:
      bms_id: '1' # must be a number
      bms_name: 'JK-BMS 1'
      bms_uart_id: 'uart_${uart_hub_bus}_4'
      # Maximum cell charging cycles is used to calculate the battey SoH.
      # MB31=8000.0, LF280K v3=8000.0, LF280K v2=6000.0, LF280=3000.0 (decimal is required)
      bms_cell_max_cycles: '6000.0'

  bms2: !include
    file: packages/bms/bms_combine_JK_UART_4G-GPS_full.yaml
    vars:
      bms_id: '2' # must be a number
      bms_name: 'JK-BMS 2'
      bms_uart_id: 'uart_${uart_hub_bus}_5'
      # Maximum cell charging cycles is used to calculate the battey SoH.
      # MB31=8000.0, LF280K v3=8000.0, LF280K v2=6000.0, LF280=3000.0 (decimal is required)
      bms_cell_max_cycles: '6000.0'

  yambms: !include packages/yambms/yambms.yaml

  canbus1: !include
    file: packages/yambms/yambms_canbus.yaml
    vars:
      canbus_id: 'canbus1'
      canbus_name: 'CANBUS 1'
      canbus_node_id: 'canbus_node1'
      canbus_light_id: 'esp_light'
      # The CANBUS link will be considered down if no response from the inverter (ID 0x305) for 5s
      # The Deye inverter sends the ACK (can_id 0x305) only when it receives the can_id 0x356
      canbus_link_timer: '5s'

# +--------------------------------------+
# | DEBUG ( logger level must be DEBUG ) |
# +--------------------------------------+

  device_debug: !include
    file: packages/base/device_debug_ESP32.yaml
    vars:
      debug_name: 'Debug'
      debug_update_interval: '5s'
