# Updated : 2025.06.26
# Version : 1.5.7
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

######################## YamBMS Local Packages Version #########################

# You need to copy the `packages` folder into the same folder as this YAML in order to compile it.
# Don't forget to configure your WiFi credentials in the secrets.yaml

################################################################################

logger:
  level: INFO # VERBOSE / DEBUG / INFO / WARN

# +--------------------------------------+
# | Global Settings                      |
# +--------------------------------------+
substitutions:
  # Name
  friendly_name : 'YamBMS' # Prefix added in front of the `entity display name`, also used to classify them.
  hostname: 'yambms' # Name of your ESPHome node registered on the IP network (DNS name, must be unique) and prefix added in front of the `entity id`.
  name: '' # This name can be added as a second prefix, both for the `entity display name` and the `entity id`, you can leave it blank.
  # +--------------------------------------+
  # | Shunt Settings                       |
  # +--------------------------------------+
  shunt_update_interval: '5s'  # frequency at which Shunt data is refreshed
  shunt_combine_interval: '1s' # frequency at which Shunt data is combined in YamBMS
  # +--------------------------------------+
  # | Modbus Settings                      |
  # +--------------------------------------+
  modbus_update_interval: '5s' # frequency with which BMS/Shunt modbus servers are queried
  modbus_baud_rate: '19200' # 9600 / 19200 / 11520
  modbus_command_throttle: '0ms' # minimum time in between 2 requests to the device
  modbus_send_wait_time: '250ms' # time in milliseconds before the next ModBUS command is sent if an answer from a previous command is pending

# +--------------------------------------+
# | Packages                             |
# +--------------------------------------+

# PLEASE READ : https://github.com/Sleeper85/esphome-yambms/blob/main/documents/README/YamBMS_main_YAML_HowTo.md

packages:

  ################ >>> CONFIG & CUSTOM LP <<< ################

  # Local Packages intended for creating custom codes
  # or sharing settings between several main.yaml

  # yambms_config: !include yambms_config.yaml
  # yambms_custom: !include yambms_custom.yaml
  ############################################################

  device_board: !include packages/board/board_RP2040_RPi_Pico.yaml

  uart_1: !include packages/board/board_options_itf_uart_1.yaml
  uart_2: !include packages/board/board_options_itf_uart_2.yaml
  uart_3: !include packages/board/board_options_itf_uart_3.yaml
  uart_4: !include packages/board/board_options_itf_uart_4.yaml
  uart_5: !include packages/board/board_options_itf_uart_5.yaml
  uart_6: !include packages/board/board_options_itf_uart_6.yaml

  modbus: !include
    file: packages/base/device_modbus.yaml
    vars:
      modbus_role: 'server' # client / server
      modbus_uart_id: 'uart_1' # RS485 board
      
  shunt1: !include
    file: packages/shunt/shunt_modbus_Victron_SmartShunt_UART_minimal.yaml
    vars:
      shunt_id: '1'
      shunt_name: 'Shunt 1'
      shunt_uart_id: 'uart_2'

  shunt2: !include
    file: packages/shunt/shunt_modbus_Victron_SmartShunt_UART_minimal.yaml
    vars:
      shunt_id: '2'
      shunt_name: 'Shunt 2'
      shunt_uart_id: 'uart_3'

  shunt3: !include
    file: packages/shunt/shunt_modbus_Victron_SmartShunt_UART_minimal.yaml
    vars:
      shunt_id: '3'
      shunt_name: 'Shunt 3'
      shunt_uart_id: 'uart_4'

  shunt4: !include
    file: packages/shunt/shunt_modbus_Victron_SmartShunt_UART_minimal.yaml
    vars:
      shunt_id: '4'
      shunt_name: 'Shunt 4'
      shunt_uart_id: 'uart_5'

  shunt5: !include
    file: packages/shunt/shunt_modbus_Victron_SmartShunt_UART_minimal.yaml
    vars:
      shunt_id: '5'
      shunt_name: 'Shunt 5'
      shunt_uart_id: 'uart_6'
