# Updated : 2026.02.01
# Version : 1.1.7
# GitHub  : https://github.com/Sleeper85/esphome-junctek_khf

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  shunt_base: !include shunt_base.yaml

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

external_components:
  - source: github://Sleeper85/esphome-junctek_khf@main
    refresh: 0s
  # - source:
  #     type: local
  #     path: components

# UART baud_rate : 115200

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

binary_sensor:
  # Required sensors cannot be retrieved from Shunt
  # online_status
  - platform: template
    id: shunt${shunt_id}_online_status
    device_id: shunt_${shunt_id}
    name: "Online status"
    lambda: |-
      if (id(shunt${shunt_id}_voltage).state > 0)
        return true;
      else
        return false;
    on_state:
      then:
        - lambda: |-
            // Pass the current state to the update function
            id(global_update_fault)(${CAT_SHUNT}, ${shunt_id}, !x);

# Platform :
# junctek_khf : version with the screen connected (UART and RS485)
# junctek_khf_rs485 : version without the screen connected (only RS485)
sensor:
  - platform: junctek_khf
    uart_id: ${shunt_uart_id}
    address: 1
    invert_current: false
    voltage:
      id: shunt${shunt_id}_voltage
      device_id: shunt_${shunt_id}
      name: "Voltage"
    current:
      id: shunt${shunt_id}_current
      device_id: shunt_${shunt_id}
      name: "Current"
    power:
      id: shunt${shunt_id}_power
      device_id: shunt_${shunt_id}
      name: "Power"
    battery_level:
      id: shunt${shunt_id}_soc
      device_id: shunt_${shunt_id}
      name: "State of Charge"
    temperature:
      device_id: shunt_${shunt_id}
      name: "Temperature"
    charged_kwh:
      device_id: shunt_${shunt_id}
      name: "Charged Energy"
    discharged_kwh:
      device_id: shunt_${shunt_id}
      name: "Discharged Energy"
    battery_capacity_ah:
      device_id: shunt_${shunt_id}
      name: "Battery Capacity"
    soc100_voltage:
      device_id: shunt_${shunt_id}
      name: "SoC 100% Voltage"
    soc0_voltage:
      device_id: shunt_${shunt_id}
      name: "SoC 0% Voltage"
    over_voltage_protection:
      device_id: shunt_${shunt_id}
      name: "Over Voltage Protection"
    under_voltage_protection:
      device_id: shunt_${shunt_id}
      name: "Under Voltage Protection"
    over_discharge_current_protection:
      device_id: shunt_${shunt_id}
      name: "Over Discharge Current Protection"
    over_charge_current_protection:
      device_id: shunt_${shunt_id}
      name: "Over Charge Current Protection"
    over_power_protection:
      device_id: shunt_${shunt_id}
      name: "Over Power Protection"
    over_temperature_protection:
      device_id: shunt_${shunt_id}
      name: "Over Temperature Protection"
    under_temperature_protection:
      device_id: shunt_${shunt_id}
      name: "Under Temperature Protection"
