# Updated : 2026.02.01
# Version : 1.7.0
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  bms_ids: '{0}'

globals:
  - id: shunt${shunt_id}_combined
    type: bool
    restore_value: no
    initial_value: "false"
  - id: shunt${shunt_id}_bms_map
    type: std::vector<uint8_t>
    initial_value: '${bms_ids}'
  - id: shunt${shunt_id}_bms_caused_uncombine
    type: int
    restore_value: no
    initial_value: "0"

# Combine once without conditions
esphome:
  on_boot:
    - priority: 600
      then:
        # Shunt counter (total)
        - lambda: id(${yambms_id}_var_shunt_counter) += 1;

switch:
  # Combine enable/disable Switch
  - platform: template
    name: "Combine enabled"
    id: shunt${shunt_id}_switch_combine
    device_id: shunt_${shunt_id}
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    on_turn_on:
      - lambda: |-
          id(shunt${shunt_id}_bms_caused_uncombine) = 0;
          id(shunt${shunt_id}_combine_state).publish_state("Enabled (switch)");
    on_turn_off:
      - lambda: |-
          if (id(shunt${shunt_id}_bms_caused_uncombine))
          {
            std::string state_msg = "Disabled (BMS " + std::to_string(id(shunt${shunt_id}_bms_caused_uncombine)) + " offline)";
            id(shunt${shunt_id}_combine_state).publish_state(state_msg.c_str());
          }
          else
          {
            id(shunt${shunt_id}_combine_state).publish_state("Disabled (switch)");
          }

binary_sensor:
  # Indicates whether the Shunt can be combined
  - platform: template
    name: "Can be combined"
    id: shunt${shunt_id}_can_be_combined
    device_id: shunt_${shunt_id}
    lambda: return (id(shunt${shunt_id}_switch_combine).state && id(shunt${shunt_id}_online_status).state);

text_sensor:
  # Show diagnostic state and reason for combine/uncombine
  - platform: template
    name: "State"
    id: shunt${shunt_id}_combine_state
    device_id: shunt_${shunt_id}
    entity_category: diagnostic
    update_interval: never
    icon: mdi:state-machine

interval:
  - interval: ${yambms_update_interval}
    then:
      - lambda: |-
          // +-----------------------------------------------+
          // | STEP 1 - Shunt combiner                       |
          // +-----------------------------------------------+
          // Shunt number to combine ?
          if (id(${yambms_id}_var_to_combine_shunt_number) == ${shunt_id})
          {
            // The Shunt can be combined ?
            if (id(shunt${shunt_id}_can_be_combined).state)
            {
              // +-----------------------------------------------+
              // | Check if all connected BMS are online         |
              // +-----------------------------------------------+
              int bms_offline = 0;
              for (auto const& bms_id : id(shunt${shunt_id}_bms_map))
              {
                if (!bms_id) continue;

                // Ignore BMS that we've not seen online yet
                if ((id(${yambms_id}_var_bms_seen_online_bitmask) & (1 << (bms_id - 1))) == 0)
                {
                  continue;
                }

                // Check if BMS is online
                if ((id(${yambms_id}_var_bms_online_bitmask) & (1 << (bms_id - 1))) == 0)
                {
                  bms_offline = bms_id;
                  break;
                }
              }

              if (bms_offline) {
                ESP_LOGI("shunt_combine", "Shunt %d: BMS %d is offline, uncombining.", ${shunt_id}, bms_offline);
                id(shunt${shunt_id}_bms_caused_uncombine) = bms_offline;
                id(shunt${shunt_id}_switch_combine).turn_off();
              }

              // +-----------------------------------------------+
              // | Combine not continuously                      |
              // +-----------------------------------------------+

              if (id(shunt${shunt_id}_combined) == false)
              {
                // To combine shunt counter
                id(${yambms_id}_var_to_combine_shunt_counter) += 1;

                // Shunt use (replace BMS infos)
                id(${yambms_id}_var_shunt_use) = true;

                // Combined
                id(shunt${shunt_id}_combined) = true;
              }

              // +-----------------------------------------------+
              // | Combine continuously                          |
              // +-----------------------------------------------+

              // TOTAL voltage
              id(${yambms_id}_var_shunt_total_voltage) += id(shunt${shunt_id}_voltage).state;
              // TOTAL current
              id(${yambms_id}_var_shunt_total_current) += id(shunt${shunt_id}_current).state;
              // TOTAL power
              id(${yambms_id}_var_shunt_total_power) += id(shunt${shunt_id}_power).state;
              // TOTAL soc
              id(${yambms_id}_var_shunt_total_soc) += id(shunt${shunt_id}_soc).state;

            }

            // +-----------------------------------------------+
            // | Uncombine not continuously                    |
            // +-----------------------------------------------+
            else if (id(shunt${shunt_id}_combined) == true)
            {
              // To combine shunt counter
              id(${yambms_id}_var_to_combine_shunt_counter) -= 1;

              // Shunt use (replace BMS infos)
              if (id(${yambms_id}_var_to_combine_shunt_counter) == 0) id(${yambms_id}_var_shunt_use) = false;

              // Uncombined
              id(shunt${shunt_id}_combined) = false;
            }

            // Increment the counter for next Shunt processing
            id(${yambms_id}_var_to_combine_shunt_number)++;
          }