# Updated : 2026.02.01
# Version : 1.1.6
# GitHub  : https://github.com/KinDR007/VictronMPPT-ESPHOME

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  shunt_base: !include shunt_base.yaml

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

external_components:
  - source: github://KinDR007/VictronMPPT-ESPHOME@main
    refresh: 0s

victron:
  - uart_id: ${shunt_uart_id}
    id: victron${shunt_id}
    throttle: ${shunt_update_interval}

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

binary_sensor:
  - platform: victron
    victron_id: victron${shunt_id}
    relay_state:
      device_id: shunt_${shunt_id}
      name: "relay state"
  # Required sensors cannot be retrieved from Shunt
  # online_status
  - platform: template
    id: shunt${shunt_id}_online_status
    device_id: shunt_${shunt_id}
    name: "Online Status"
    lambda: |-
      if (id(shunt${shunt_id}_voltage).state > 0)
        return true;
      else
        return false;
    on_state:
      then:
        - lambda: |-
            // Pass the current state to the update function
            id(global_update_fault)(${CAT_SHUNT}, ${shunt_id}, !x);

sensor:
  - platform: victron
    victron_id: victron${shunt_id}
    # Minimal sensors
    battery_voltage:
      id: shunt${shunt_id}_voltage
      device_id: shunt_${shunt_id}
      name: "Voltage"
    battery_current:
      id: shunt${shunt_id}_current
      device_id: shunt_${shunt_id}
      name: "Current"
    instantaneous_power:
      id: shunt${shunt_id}_power
      device_id: shunt_${shunt_id}
      name: "Power"
    state_of_charge:
      id: shunt${shunt_id}_soc
      device_id: shunt_${shunt_id}
      name: "State of charge"
    # Extras sensors
    auxiliary_battery_voltage:
      device_id: shunt_${shunt_id}
      name: "auxiliary battery voltage"
    midpoint_voltage_of_the_battery_bank:
      device_id: shunt_${shunt_id}
      name: "midpoint voltage of the battery bank"
    midpoint_deviation_of_the_battery_bank:
      device_id: shunt_${shunt_id}
      name: "midpoint deviation of the battery bank"
    battery_temperature:
      device_id: shunt_${shunt_id}
      name: "battery temperature"
    consumed_amp_hours:
      device_id: shunt_${shunt_id}
      name: "consumed amp hours"
    time_to_go:
      device_id: shunt_${shunt_id}
      name: "time to go"
    depth_of_the_deepest_discharge:
      device_id: shunt_${shunt_id}
      name: "depth of the deepest discharge"
    depth_of_the_last_discharge:
      device_id: shunt_${shunt_id}
      name: "depth of the last discharge"
    depth_of_the_average_discharge:
      device_id: shunt_${shunt_id}
      name: "depth of the average discharge"
    number_of_charge_cycles:
      device_id: shunt_${shunt_id}
      name: "number of charge cycles"
    number_of_full_discharges:
      device_id: shunt_${shunt_id}
      name: "number of full discharges"
    cumulative_amp_hours_drawn:
      device_id: shunt_${shunt_id}
      name: "cumulative amp hours drawn"
    min_battery_voltage:
      device_id: shunt_${shunt_id}
      name: "min battery voltage"
    max_battery_voltage:
      device_id: shunt_${shunt_id}
      name: "max battery voltage"
    last_full_charge:
      device_id: shunt_${shunt_id}
      name: "last full charge"
    number_of_automatic_synchronizations:
      device_id: shunt_${shunt_id}
      name: "number of automatic synchronizations"
    number_of_low_main_voltage_alarms:
      device_id: shunt_${shunt_id}
      name: "number of low main voltage alarms"
    number_of_high_main_voltage_alarms:
      device_id: shunt_${shunt_id}
      name: "number of high main voltage alarms"
    number_of_low_auxiliary_voltage_alarms:
      device_id: shunt_${shunt_id}
      name: "number of low auxiliary voltage alarms"
    number_of_high_auxiliary_voltage_alarms:
      device_id: shunt_${shunt_id}
      name: "number of high auxiliary voltage alarms"
    min_auxiliary_battery_voltage:
      device_id: shunt_${shunt_id}
      name: "min auxiliary battery voltage"
    max_auxiliary_battery_voltage:
      device_id: shunt_${shunt_id}
      name: "max auxiliary battery voltage"
    amount_of_discharged_energy:
      device_id: shunt_${shunt_id}
      name: "amount of discharged energy"
    amount_of_charged_energy:
      device_id: shunt_${shunt_id}
      name: "amount of charged energy"
    dc_monitor_mode_id:
      device_id: shunt_${shunt_id}
      name: "dc monitor mode id"

text_sensor:
  - platform: victron
    victron_id: victron${shunt_id}
    alarm_condition_active:
      device_id: shunt_${shunt_id}
      name: "alarm condition active"
    alarm_reason:
      device_id: shunt_${shunt_id}
      name: "alarm reason"
    model_description:
      device_id: shunt_${shunt_id}
      name: "model description"
    firmware_version:
      device_id: shunt_${shunt_id}
      name: "firmware version"
    device_type:
      device_id: shunt_${shunt_id}
      name: "device type"
    serial_number:
      device_id: shunt_${shunt_id}
      name: "serial number"
    dc_monitor_mode:
      device_id: shunt_${shunt_id}
      name: "dc monitor mode"
