# Updated : 2025.12.22
# Version : 1.1.6
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  shunt_base: !include shunt_base.yaml

binary_sensor:
  # Required sensors cannot be retrieved from Shunt
  # online_status
  - platform: template
    id: shunt${shunt_id}_online_status
    device_id: shunt_${shunt_id}
    name: "Online status"
    lambda: |-
      if (id(shunt${shunt_id}_voltage).state > 0)
        return true;
      else
        return false;

sensor:
  # total_voltage
  - platform: template
    id: shunt${shunt_id}_voltage
    device_id: shunt_${shunt_id}
    name: "Voltage"
    update_interval: ${shunt_update_interval}
    accuracy_decimals: 2
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.01
    lambda: return ${shunt_voltage};

  # current
  - platform: template
    id: shunt${shunt_id}_current
    device_id: shunt_${shunt_id}
    name: "Current"
    update_interval: ${shunt_update_interval}
    accuracy_decimals: 1
    unit_of_measurement: A
    device_class: current
    filters:
      - or:
        - throttle: 10s
        - delta: 0.1
    lambda: return ${shunt_current};

  # power
  - platform: template
    id: shunt${shunt_id}_power
    device_id: shunt_${shunt_id}
    name: "Power"
    update_interval: ${shunt_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: W
    device_class: power
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${shunt_power};

  # state_of_charge
  - platform: template
    id: shunt${shunt_id}_soc
    device_id: shunt_${shunt_id}
    name: "State of Charge"
    update_interval: ${shunt_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: '%'
    device_class: battery
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${shunt_soc};
