# Updated : 2025.12.22
# Version : 1.3.3
# GitHub  : https://github.com/syssi/esphome-jk-bms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  bms_model: "JK"
  bms_protocol: "UART 4G-GPS"

packages:
  bms_base: !include bms_base.yaml
  bms_combine: !include bms_combine.yaml
  bms_temperature_sensor: !include bms_temperature_sensor_2.yaml
  bms_errors_bitmask: !include bms_errors_bitmask_JK_UART_4G-GPS.yaml
  bms_battery_soh: !include bms_base_battery_soh.yaml

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

external_components:
  - source: github://syssi/esphome-jk-bms@main
    refresh: 0s

jk_modbus:
  - id: jk_modbus${bms_id}
    uart_id: ${bms_uart_id}

jk_bms:
  - id: jk_bms${bms_id}
    jk_modbus_id: jk_modbus${bms_id}
    update_interval: ${bms_update_interval}

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

binary_sensor:
  - platform: jk_bms
    jk_bms_id: jk_bms${bms_id}
    balancing:
      id: bms${bms_id}_bms_equalizing
      device_id: bms_${bms_id}
      # name: "balancing"
    balancing_switch:
      device_id: bms_${bms_id}
      name: "balancing switch"
    charging:
      id: bms${bms_id}_charging_allowed
      device_id: bms_${bms_id}
      name: "charging"
    charging_switch:
      device_id: bms_${bms_id}
      name: "charging switch"
    discharging:
      id: bms${bms_id}_discharging_allowed
      device_id: bms_${bms_id}
      name: "discharging"
    discharging_switch:
      device_id: bms_${bms_id}
      name: "discharging switch"
    dedicated_charger_switch:
      device_id: bms_${bms_id}
      name: "dedicated charger switch"

switch:
  - platform: jk_bms
    jk_bms_id: jk_bms${bms_id}
    charging:
      id: bms${bms_id}_charge_switch
      device_id: bms_${bms_id}
      name: "Charge switch"
    discharging:
      id: bms${bms_id}_discharge_switch
      device_id: bms_${bms_id}
      name: "Discharge switch"
    # It is not possible to control the balancer from UART-TTL (confirmed by @syssi)

sensor:
  - platform: jk_bms
    jk_bms_id: jk_bms${bms_id}
    min_cell_voltage:
      id: bms${bms_id}_min_cell_voltage
      device_id: bms_${bms_id}
      name: "min cell voltage"
    max_cell_voltage:
      id: bms${bms_id}_max_cell_voltage
      device_id: bms_${bms_id}
      name: "max cell voltage"
    min_voltage_cell:
      id: bms${bms_id}_min_voltage_cell
      device_id: bms_${bms_id}
      name: "min voltage cell"
    max_voltage_cell:
      id: bms${bms_id}_max_voltage_cell
      device_id: bms_${bms_id}
      name: "max voltage cell"
    delta_cell_voltage:
      id: bms${bms_id}_delta_cell_voltage
      device_id: bms_${bms_id}
      name: "delta cell voltage"
    average_cell_voltage:
      id: bms${bms_id}_average_cell_voltage
      device_id: bms_${bms_id}
      name: "average cell voltage"
    power_tube_temperature:
      id: bms${bms_id}_power_tube_temperature
      device_id: bms_${bms_id}
      name: "power tube temperature"
    temperature_sensor_1:
      id: bms${bms_id}_temperature_sensor_1
      device_id: bms_${bms_id}
      name: "temperature sensor 1"
    temperature_sensor_2:
      id: bms${bms_id}_temperature_sensor_2
      device_id: bms_${bms_id}
      name: "temperature sensor 2"
    total_voltage:
      id: bms${bms_id}_total_voltage
      device_id: bms_${bms_id}
      name: "total voltage"
    current:
      id: bms${bms_id}_current
      device_id: bms_${bms_id}
      name: "current"
    power:
      id: bms${bms_id}_power
      device_id: bms_${bms_id}
      name: "power"
    charging_power:
      id: bms${bms_id}_charging_power
      device_id: bms_${bms_id}
      name: "charging power"
    discharging_power:
      id: bms${bms_id}_discharging_power
      device_id: bms_${bms_id}
      name: "discharging power"
    capacity_remaining:
      id: bms${bms_id}_state_of_charge
      device_id: bms_${bms_id}
      # name: "state of charge"
    capacity_remaining_derived:
      id: bms${bms_id}_capacity_remaining_ah
      device_id: bms_${bms_id}
      # name: "capacity remaining"
    temperature_sensors:
      device_id: bms_${bms_id}
      name: "temperature sensors"
      entity_category: diagnostic
    charging_cycles:
      id: bms${bms_id}_charging_cycles_raw
      device_id: bms_${bms_id}
      # name: "charging cycles"
    total_charging_cycle_capacity:
      id: bms${bms_id}_cycle_capacity_raw
      device_id: bms_${bms_id}
      # name: "total charging cycle capacity"
    battery_strings:
      id: bms${bms_id}_cell_count
      device_id: bms_${bms_id}
      name: "battery strings"
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      device_id: bms_${bms_id}
      name: "errors bitmask"
      entity_category: diagnostic
    total_voltage_overvoltage_protection:
      device_id: bms_${bms_id}
      name: "total voltage overvoltage protection"
    total_voltage_undervoltage_protection:
      id: bms${bms_id}_total_uvp
      device_id: bms_${bms_id}
      name: "total voltage undervoltage protection"
    cell_voltage_overvoltage_protection:
      id: bms${bms_id}_cell_ovp
      device_id: bms_${bms_id}
      name: "cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      id: bms${bms_id}_cell_ovpr
      device_id: bms_${bms_id}
      name: "cell voltage overvoltage recovery"
    cell_voltage_overvoltage_delay:
      device_id: bms_${bms_id}
      name: "cell voltage overvoltage delay"
    cell_voltage_undervoltage_protection:
      id: bms${bms_id}_cell_uvp
      device_id: bms_${bms_id}
      name: "cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      id: bms${bms_id}_cell_uvpr
      device_id: bms_${bms_id}
      name: "cell voltage undervoltage recovery"
    cell_voltage_undervoltage_delay:
      device_id: bms_${bms_id}
      name: "cell voltage undervoltage delay"
    cell_pressure_difference_protection:
      device_id: bms_${bms_id}
      name: "cell pressure difference protection"
    discharging_overcurrent_protection:
      id: bms${bms_id}_max_discharge_current
      device_id: bms_${bms_id}
      name: "discharging overcurrent protection"
    discharging_overcurrent_delay:
      device_id: bms_${bms_id}
      name: "discharging overcurrent delay"
    charging_overcurrent_protection:
      id: bms${bms_id}_max_charge_current
      device_id: bms_${bms_id}
      name: "charging overcurrent protection"
    charging_overcurrent_delay:
      device_id: bms_${bms_id}
      name: "charging overcurrent delay"
    balance_starting_voltage:
      id: bms${bms_id}_balance_starting_voltage
      device_id: bms_${bms_id}
      name: "balance starting voltage"
    balance_opening_pressure_difference:
      id: bms${bms_id}_bms_balance_trigger_voltage
      device_id: bms_${bms_id}
      # name: "balance opening pressure difference"
    power_tube_temperature_protection:
      device_id: bms_${bms_id}
      name: "power tube temperature protection"
    power_tube_temperature_recovery:
      device_id: bms_${bms_id}
      name: "power tube temperature recovery"
    temperature_sensor_temperature_protection:
      device_id: bms_${bms_id}
      name: "temperature sensor temperature protection"
    temperature_sensor_temperature_recovery:
      device_id: bms_${bms_id}
      name: "temperature sensor temperature recovery"
    temperature_sensor_temperature_difference_protection:
      device_id: bms_${bms_id}
      name: "temperature sensor temperature difference protection"
    charging_high_temperature_protection:
      device_id: bms_${bms_id}
      name: "charging high temperature protection"
    discharging_high_temperature_protection:
      device_id: bms_${bms_id}
      name: "discharging high temperature protection"
    charging_low_temperature_protection:
      device_id: bms_${bms_id}
      name: "charging low temperature protection"
    charging_low_temperature_recovery:
      device_id: bms_${bms_id}
      name: "charging low temperature recovery"
    discharging_low_temperature_protection:
      device_id: bms_${bms_id}
      name: "discharging low temperature protection"
    discharging_low_temperature_recovery:
      device_id: bms_${bms_id}
      name: "discharging low temperature recovery"
    total_battery_capacity_setting:
      id: bms${bms_id}_battery_capacity
      device_id: bms_${bms_id}
      name: "total battery capacity setting"

text_sensor:
  - platform: jk_bms
    jk_bms_id: jk_bms${bms_id}
    errors:
      device_id: bms_${bms_id}
      name: "errors"
      entity_category: diagnostic
    operation_mode:
      device_id: bms_${bms_id}
      name: "operation mode"
      entity_category: diagnostic
    battery_type:
      device_id: bms_${bms_id}
      name: "battery type"
      entity_category: diagnostic
    # password:
    #   name: "password"
    device_type:
      device_id: bms_${bms_id}
      name: "device type"
      entity_category: diagnostic
    software_version:
      device_id: bms_${bms_id}
      name: "software version"
      entity_category: diagnostic
    manufacturer:
      device_id: bms_${bms_id}
      name: "manufacturer"
      entity_category: diagnostic
    total_runtime_formatted:
      device_id: bms_${bms_id}
      name: "total runtime formatted"
      entity_category: diagnostic
