# Updated : 2025.12.22
# Version : 1.3.2
# GitHub  : https://github.com/txubelaxu/esphome-jk-bms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  bms_model: "JK"
  bms_protocol: "RS485"
  sniffer_id: "jk_sniffer_1"
  sniffer_name: "JK sniffer"

packages:
  modbus_sniffer: !include bms_base_sniffer_sub_device.yaml

logger:
  tx_buffer_size: 1024

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

external_components:
  - source: github://Sleeper85/esphome-components@main
    refresh: 0s
    components: [ jk_rs485_sniffer , jk_rs485_bms ]
  # - source:
  #     type: local
  #     path: ../esphome-components/components

jk_rs485_sniffer:
  - id: ${sniffer_id}
    protocol_version: ${sniffer_protocol}
    rx_timeout: 500ms
    uart_id: ${sniffer_uart_id}
    talk_pin: ${sniffer_talk_pin}

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

switch:
  - platform: template
    device_id: sniffer_${sniffer_uart_id}
    name: "Broadcasting BMS settings to all BMS"
    icon: "mdi:cast"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    entity_category: config
    turn_on_action:
      - lambda: id(${sniffer_id}).set_broadcast_changes_to_all_bms(true);
    turn_off_action:
      - lambda: id(${sniffer_id}).set_broadcast_changes_to_all_bms(false);
