# Updated : 2026.02.03
# Version : 1.2.4
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  balancer: !include bms_base_balancer.yaml
  bms_battery_soc: !include bms_base_battery_soc.yaml
  sub_device: !include bms_base_sub_device.yaml
  led_assign: !include bms_base_led_assign.yaml
  # bms_temperature_sensor: !include bms_temperature_sensor_4.yaml

number:
  # errors_bitmask (16bits)
  - platform: template
    id: bms${bms_id}_yambms_errors_bitmask_number
    device_id: bms_${bms_id}
    name: "YamBMS Errors Bitmask"
    mode: box
    step: 1
    min_value: 0
    max_value: 65535
    restore_value: true
    initial_value: 0 # 0~65535 (16bits) 0=NoAlarm
    icon: mdi:alert-circle-outline
    optimistic: true
    entity_category: config
  # min_cell_voltage
  - platform: template
    id: bms${bms_id}_min_cell_voltage
    device_id: bms_${bms_id}
    name: "min cell voltage"
    mode: box
    step: 0.005
    min_value: 2.5
    max_value: 3.65
    restore_value: true
    initial_value: ${bms_min_cell_voltage}
    device_class: voltage
    optimistic: true
    entity_category: config
  # max_cell_voltage
  - platform: template
    id: bms${bms_id}_max_cell_voltage
    device_id: bms_${bms_id}
    name: "max cell voltage"
    mode: box
    step: 0.005
    min_value: 2.5
    max_value: 3.65
    restore_value: true
    initial_value: ${bms_max_cell_voltage}
    device_class: voltage
    optimistic: true
    entity_category: config
  # min_temperature
  - platform: template
    id: bms${bms_id}_min_temperature
    device_id: bms_${bms_id}
    name: "min temperature"
    mode: box
    step: 0.1
    min_value: -30.0
    max_value: 60.0
    restore_value: true
    initial_value: ${bms_min_temperature}
    unit_of_measurement: °C
    device_class: temperature
    optimistic: true
    entity_category: config
  # max_temperature
  - platform: template
    id: bms${bms_id}_max_temperature
    device_id: bms_${bms_id}
    name: "max temperature"
    mode: box
    step: 0.1
    min_value: -30.0
    max_value: 60.0
    restore_value: true
    initial_value: ${bms_max_temperature}
    unit_of_measurement: °C
    device_class: temperature
    optimistic: true
    entity_category: config

switch:
  - platform: template
    id: bms${bms_id}_online_status_switch
    device_id: bms_${bms_id}
    name: "online status switch"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: bms${bms_id}_charging_allowed_switch
    device_id: bms_${bms_id}
    name: "charge switch"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: bms${bms_id}_discharging_allowed_switch
    device_id: bms_${bms_id}
    name: "discharge switch"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
  - platform: template
    id: bms${bms_id}_equalizing_switch
    device_id: bms_${bms_id}
    name: "balance switch"
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true

binary_sensor:
  # online_status
  - platform: template
    id: bms${bms_id}_online_status
    device_id: bms_${bms_id}
    name: "online status"
    lambda: return id(bms${bms_id}_online_status_switch).state;
    on_state:
      then:
        - lambda: |-
            // Pass the current state to the update function
            id(global_update_fault)(${CAT_BMS}, ${bms_id}, !x);
  # charging_allowed
  - platform: template
    id: bms${bms_id}_charging_allowed
    device_id: bms_${bms_id}
    name: "charging"
    lambda: return id(bms${bms_id}_charging_allowed_switch).state;
  # discharging_allowed
  - platform: template
    id: bms${bms_id}_discharging_allowed
    device_id: bms_${bms_id}
    name: "discharging"
    lambda: return id(bms${bms_id}_discharging_allowed_switch).state;
  # equalizing
  - platform: template
    id: bms${bms_id}_bms_equalizing
    device_id: bms_${bms_id}
    name: "balancing"
    lambda: return id(bms${bms_id}_equalizing_switch).state;

sensor:
  # battery_capacity
  - platform: template
    id: bms${bms_id}_battery_capacity
    device_id: bms_${bms_id}
    name: "Battery Capacity"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: Ah
    icon: mdi:car-battery
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_battery_capacity};

  # capacity_remaining_ah
  - platform: template
    id: bms${bms_id}_capacity_remaining_ah
    device_id: bms_${bms_id}
    # name: "Battery Capacity Remaining"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: Ah
    icon: mdi:car-battery
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_battery_capacity_remaining};

  # total_voltage
  - platform: template
    id: bms${bms_id}_total_voltage
    device_id: bms_${bms_id}
    name: "Total Voltage"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 2
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.01
    lambda: return ${bms_voltage};

  # current
  - platform: template
    id: bms${bms_id}_current
    device_id: bms_${bms_id}
    name: "Current"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 1
    unit_of_measurement: A
    device_class: current
    filters:
      - or:
        - throttle: 10s
        - delta: 0.1
    lambda: return ${bms_current};

  # power
  - platform: template
    id: bms${bms_id}_power
    device_id: bms_${bms_id}
    name: "Power"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: W
    device_class: power
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_power};

  # battery_soc
  - platform: template
    id: bms${bms_id}_state_of_charge
    device_id: bms_${bms_id}
    # name: "Battery SoC"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: '%'
    device_class: battery
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_soc};

  # battery_soh
  - platform: template
    id: bms${bms_id}_battery_soh
    device_id: bms_${bms_id}
    name: "Battery SoH"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: '%'
    device_class: battery
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_soh};

  # min_voltage_cell
  - platform: template
    id: bms${bms_id}_min_voltage_cell
    device_id: bms_${bms_id}
    name: "Min Voltage Cell"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    icon: mdi:numeric
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_min_voltage_cell};

  # max_voltage_cell
  - platform: template
    id: bms${bms_id}_max_voltage_cell
    device_id: bms_${bms_id}
    name: "Max Voltage Cell"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    icon: mdi:numeric
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_max_voltage_cell};

  # MIN temperature sensor
  - platform: template
    id: bms${bms_id}_min_temperature_sensor
    device_id: bms_${bms_id}
    name: "min temperature sensor"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    icon: mdi:numeric
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_id}01;

  # MAX temperature sensor
  - platform: template
    id: bms${bms_id}_max_temperature_sensor
    device_id: bms_${bms_id}
    name: "max temperature sensor"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    icon: mdi:numeric
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_id}02;

  # max_charge_current
  - platform: template
    id: bms${bms_id}_max_charge_current
    device_id: bms_${bms_id}
    name: "Max Charge Current"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: A
    icon: mdi:current-dc
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_max_charge_current};

  # max_discharge_current
  - platform: template
    id: bms${bms_id}_max_discharge_current
    device_id: bms_${bms_id}
    name: "Max Discharge Current"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: A
    icon: mdi:current-dc
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_max_discharge_current};

  # cell_ovp
  - platform: template
    id: bms${bms_id}_cell_ovp
    device_id: bms_${bms_id}
    name: "Cell OVP"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return ${bms_cell_ovp};

  # cell_uvp
  - platform: template
    id: bms${bms_id}_cell_uvp
    device_id: bms_${bms_id}
    name: "Cell UVP"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return ${bms_cell_uvp};

  # balance_trigger_voltage
  - platform: template
    id: bms${bms_id}_bms_balance_trigger_voltage
    device_id: bms_${bms_id}
    name: "BMS balance trigger voltage"
    internal: true
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return ${bms_balance_trigger_voltage};

  # charging_cycles
  - platform: template
    id: bms${bms_id}_charging_cycles
    device_id: bms_${bms_id}
    name: "charging cycles"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    icon: mdi:counter
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_charging_cycles};

  # Charging power: Calculated from voltage and current
  - platform: template
    id: bms${bms_id}_charging_power
    device_id: bms_${bms_id}
    name: "battery power charging"
    update_interval: ${bms_update_interval}
    unit_of_measurement: 'W'
    device_class: 'current'
    state_class: 'measurement'
    accuracy_decimals: 0
    lambda: |-
      if (id(bms${bms_id}_current).state > 0) return id(bms${bms_id}_total_voltage).state * id(bms${bms_id}_current).state;
      else return 0;

  # Discharging power: Calculated from voltage and current
  - platform: template
    id: bms${bms_id}_discharging_power
    device_id: bms_${bms_id}
    name: "battery power discharging"
    update_interval: ${bms_update_interval}
    unit_of_measurement: 'W'
    device_class: 'current'
    state_class: 'measurement'
    accuracy_decimals: 0
    lambda: |-
      if (id(bms${bms_id}_current).state < 0) return id(bms${bms_id}_total_voltage).state * -id(bms${bms_id}_current).state;
      else return 0;

  # errors_bitmask (internal)
  - platform: template
    id: bms${bms_id}_yambms_errors_bitmask
    device_id: bms_${bms_id}
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    icon: mdi:alert-circle-outline
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return id(bms${bms_id}_yambms_errors_bitmask_number).state;

  # # temperature_sensor_1
  # - platform: template
  #   id: bms${bms_id}_temperature_sensor_1
  #   device_id: bms_${bms_id}
  #   name: "Temperature Sensor 1"
  #   update_interval: ${bms_update_interval}
  #   accuracy_decimals: 1
  #   unit_of_measurement: °C
  #   device_class: temperature
  #   filters:
  #     - or:
  #       - throttle: 10s
  #       - delta: 0.1
  #   lambda: return ${bms_temperature_sensor_1};

  # # temperature_sensor_2
  # - platform: template
  #   id: bms${bms_id}_temperature_sensor_2
  #   device_id: bms_${bms_id}
  #   name: "Temperature Sensor 2"
  #   update_interval: ${bms_update_interval}
  #   accuracy_decimals: 1
  #   unit_of_measurement: °C
  #   device_class: temperature
  #   filters:
  #     - or:
  #       - throttle: 10s
  #       - delta: 0.1
  #   lambda: return ${bms_temperature_sensor_2};

  # # temperature_sensor_3
  # - platform: template
  #   id: bms${bms_id}_temperature_sensor_3
  #   device_id: bms_${bms_id}
  #   name: "Temperature Sensor 3"
  #   update_interval: ${bms_update_interval}
  #   accuracy_decimals: 1
  #   unit_of_measurement: °C
  #   device_class: temperature
  #   filters:
  #     - or:
  #       - throttle: 10s
  #       - delta: 0.1
  #   lambda: return ${bms_temperature_sensor_3};

  # # temperature_sensor_4
  # - platform: template
  #   id: bms${bms_id}_temperature_sensor_4
  #   device_id: bms_${bms_id}
  #   name: "Temperature Sensor 4"
  #   update_interval: ${bms_update_interval}
  #   accuracy_decimals: 1
  #   unit_of_measurement: °C
  #   device_class: temperature
  #   filters:
  #     - or:
  #       - throttle: 10s
  #       - delta: 0.1
  #   lambda: return ${bms_temperature_sensor_4};
