# Updated : 2025.12.22
# Version : 1.2.0
# GitHub  : https://github.com/syssi/esphome-jdb-bms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  bms_base: !include bms_base.yaml
  bms_temperature_sensor: !include bms_temperature_sensor_6.yaml
  bms_errors_bitmask: !include bms_errors_bitmask_JBD.yaml
  bms_battery_soh: !include bms_base_battery_soh.yaml

ota:
  on_begin:
    then:
      - switch.turn_off: bms${bms_id}_enable_bluetooth_connection
      - logger.log: "BLE shutdown for flashing"

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

external_components:
  - source: github://syssi/esphome-jbd-bms@main
    refresh: 0s

esp32_ble_tracker:
  scan_parameters:
    active: false

ble_client:
  - id: ble_client${bms_id}
    mac_address: ${bms_ble_mac_address}

jbd_bms_ble:
  - id: jbd_bms_ble${bms_id}
    ble_client_id: ble_client${bms_id}
    update_interval: ${bms_update_interval} # Some Liontron BMS models require an update interval of less than 8s

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

button:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: jbd_bms_ble${bms_id}
    retrieve_hardware_version:
      device_id: bms_${bms_id}
      name: "retrieve hardware version"

binary_sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: jbd_bms_ble${bms_id}
    balancing:
      id: bms${bms_id}_bms_equalizing
      device_id: bms_${bms_id}
      # name: "balancing"
    charging:
      id: bms${bms_id}_charging_allowed
      device_id: bms_${bms_id}
      name: "charging"
    discharging:
      id: bms${bms_id}_discharging_allowed
      device_id: bms_${bms_id}
      name: "discharging"
    online_status:
      id: bms${bms_id}_online_status
      device_id: bms_${bms_id}
      name: "online status"

switch:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: jbd_bms_ble${bms_id}
    charging:
      id: bms${bms_id}_charge_switch
      device_id: bms_${bms_id}
      name: "Charge switch"
    discharging:
      id: bms${bms_id}_discharge_switch
      device_id: bms_${bms_id}
      name: "Discharge switch"
  # +--------------------------------------+
  - platform: ble_client
    ble_client_id: ble_client${bms_id}
    id: bms${bms_id}_enable_bluetooth_connection
    device_id: bms_${bms_id}
    name: "${bms_name} Enable Bluetooth connection"
  # +--------------------------------------+

sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: jbd_bms_ble${bms_id}
    battery_strings:
      device_id: bms_${bms_id}
      name: "battery strings"
    current:
      id: bms${bms_id}_current
      device_id: bms_${bms_id}
      name: "current"
    power:
      id: bms${bms_id}_power
      device_id: bms_${bms_id}
      name: "power"
    charging_power:
      id: bms${bms_id}_charging_power
      device_id: bms_${bms_id}
      name: "charging power"
    discharging_power:
      id: bms${bms_id}_discharging_power
      device_id: bms_${bms_id}
      name: "discharging power"
    state_of_charge:
      id: bms${bms_id}_state_of_charge
      device_id: bms_${bms_id}
      # name: "state of charge"
    nominal_capacity:
      id: bms${bms_id}_battery_capacity
      device_id: bms_${bms_id}
      name: "nominal capacity"
    charging_cycles:
      id: bms${bms_id}_charging_cycles_raw
      device_id: bms_${bms_id}
      # name: "charging cycles"
    capacity_remaining:
      id: bms${bms_id}_capacity_remaining_ah
      device_id: bms_${bms_id}
      # name: "capacity remaining"
    # battery_cycle_capacity:
    #   name: "battery cycle capacity" # https://github.com/syssi/esphome-jbd-bms/issues/143
    total_voltage:
      id: bms${bms_id}_total_voltage
      device_id: bms_${bms_id}
      name: "total voltage"
    average_cell_voltage:
      id: bms${bms_id}_average_cell_voltage
      device_id: bms_${bms_id}
      name: "average cell voltage"
    delta_cell_voltage:
      id: bms${bms_id}_delta_cell_voltage
      device_id: bms_${bms_id}
      name: "delta cell voltage"
    min_cell_voltage:
      id: bms${bms_id}_min_cell_voltage
      device_id: bms_${bms_id}
      name: "min cell voltage"
    max_cell_voltage:
      id: bms${bms_id}_max_cell_voltage
      device_id: bms_${bms_id}
      name: "max cell voltage"
    min_voltage_cell:
      id: bms${bms_id}_min_voltage_cell
      device_id: bms_${bms_id}
      name: "min voltage cell"
    max_voltage_cell:
      id: bms${bms_id}_max_voltage_cell
      device_id: bms_${bms_id}
      name: "max voltage cell"
    temperature_1:
      id: bms${bms_id}_temperature_sensor_1
      device_id: bms_${bms_id}
      name: "temperature 1"
    temperature_2:
      id: bms${bms_id}_temperature_sensor_2
      device_id: bms_${bms_id}
      name: "temperature 2"
    temperature_3:
      id: bms${bms_id}_temperature_sensor_3
      device_id: bms_${bms_id}
      name: "temperature 3"
    temperature_4:
      id: bms${bms_id}_temperature_sensor_4
      device_id: bms_${bms_id}
      name: "temperature 4"
    temperature_5:
      id: bms${bms_id}_temperature_sensor_5
      device_id: bms_${bms_id}
      name: "temperature 5"
    temperature_6:
      id: bms${bms_id}_temperature_sensor_6
      device_id: bms_${bms_id}
      name: "temperature 6"
    cell_voltage_1:
      device_id: bms_${bms_id}
      name: "cell voltage 1"
    cell_voltage_2:
      device_id: bms_${bms_id}
      name: "cell voltage 2"
    cell_voltage_3:
      device_id: bms_${bms_id}
      name: "cell voltage 3"
    cell_voltage_4:
      device_id: bms_${bms_id}
      name: "cell voltage 4"
    cell_voltage_5:
      device_id: bms_${bms_id}
      name: "cell voltage 5"
    cell_voltage_6:
      device_id: bms_${bms_id}
      name: "cell voltage 6"
    cell_voltage_7:
      device_id: bms_${bms_id}
      name: "cell voltage 7"
    cell_voltage_8:
      device_id: bms_${bms_id}
      name: "cell voltage 8"
    cell_voltage_9:
      device_id: bms_${bms_id}
      name: "cell voltage 9"
    cell_voltage_10:
      device_id: bms_${bms_id}
      name: "cell voltage 10"
    cell_voltage_11:
      device_id: bms_${bms_id}
      name: "cell voltage 11"
    cell_voltage_12:
      device_id: bms_${bms_id}
      name: "cell voltage 12"
    cell_voltage_13:
      device_id: bms_${bms_id}
      name: "cell voltage 13"
    cell_voltage_14:
      device_id: bms_${bms_id}
      name: "cell voltage 14"
    cell_voltage_15:
      device_id: bms_${bms_id}
      name: "cell voltage 15"
    cell_voltage_16:
      device_id: bms_${bms_id}
      name: "cell voltage 16"
    # cell_voltage_17:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 17"
    # cell_voltage_18:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 18"
    # cell_voltage_19:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 19"
    # cell_voltage_20:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 20"
    # cell_voltage_21:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 21"
    # cell_voltage_22:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 22"
    # cell_voltage_23:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 23"
    # cell_voltage_24:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 24"
    # cell_voltage_25:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 25"
    # cell_voltage_26:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 26"
    # cell_voltage_27:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 27"
    # cell_voltage_28:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 28"
    # cell_voltage_29:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 29"
    # cell_voltage_30:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 30"
    # cell_voltage_31:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 31"
    # cell_voltage_32:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 32"
    operation_status_bitmask:
      device_id: bms_${bms_id}
      name: "operation status bitmask"
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      device_id: bms_${bms_id}
      name: "errors bitmask"
    balancer_status_bitmask:
      device_id: bms_${bms_id}
      name: "balancer status bitmask"
    software_version:
      device_id: bms_${bms_id}
      name: "software version"

  # Required sensors cannot be retrieved from BMS
  # max_charge_current
  - platform: template
    id: bms${bms_id}_max_charge_current
    device_id: bms_${bms_id}
    name: "max charge current"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: A
    icon: mdi:current-dc
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_max_charge_current};
  # max_discharge_current
  - platform: template
    id: bms${bms_id}_max_discharge_current
    device_id: bms_${bms_id}
    name: "max discharge current"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: A
    icon: mdi:current-dc
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return ${bms_max_discharge_current};
  # cell_ovp
  - platform: template
    id: bms${bms_id}_cell_ovp
    device_id: bms_${bms_id}
    name: "cell ovp"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return ${bms_cell_ovp};
  # cell_uvp
  - platform: template
    id: bms${bms_id}_cell_uvp
    device_id: bms_${bms_id}
    name: "cell uvp"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return ${bms_cell_uvp};
  # balance_trigger_voltage
  - platform: template
    id: bms${bms_id}_bms_balance_trigger_voltage
    device_id: bms_${bms_id}
    # name: "balance trigger voltage"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: V
    device_class: voltage
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return ${bms_balance_trigger_voltage};

  # Charging cycle capacity - Calculated from charging cycles and battery capacity
  - platform: template
    id: bms${bms_id}_cycle_capacity_raw
    device_id: bms_${bms_id}
    # name: "charging cycle capacity"
    update_interval: ${bms_update_interval}
    unit_of_measurement: Ah
    state_class: total
    icon: mdi:car-battery
    accuracy_decimals: 0
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return id(bms${bms_id}_charging_cycles_raw).state * id(bms${bms_id}_battery_capacity).state;

text_sensor:
  - platform: jbd_bms_ble
    jbd_bms_ble_id: jbd_bms_ble${bms_id}
    errors:
      device_id: bms_${bms_id}
      name: "errors"
    operation_status:
      device_id: bms_${bms_id}
      name: "operation status"
    device_model:
      device_id: bms_${bms_id}
      name: "device model"
