# Updated : 2025.12.09
# Version : 1.3.2
# GitHub  : https://github.com/txubelaxu/esphome-jk-bms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  bms_base: !include bms_base.yaml
  bms_combine: !include bms_combine.yaml
  bms_temperature_sensor: !include bms_temperature_sensor_5.yaml
  bms_errors_bitmask: !include bms_errors_bitmask_JK_RS485_Modbus.yaml

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

jk_rs485_bms:
  - id: jk_rs485_bms${bms_id}
    rs485_address: ${bms_address}
    jk_rs485_sniffer_id: ${sniffer_id}
    update_interval: ${bms_update_interval}

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

switch:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    precharging:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} precharging"
    charging:
      id: bms${bms_id}_charge_switch
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} charging"
    discharging:
      id: bms${bms_id}_discharge_switch
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} discharging"
    balancing:
      id: bms${bms_id}_balance_switch
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} balancing"
    emergency:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} emergency"
    heating:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} heating"
    display_always_on:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} display_always_on"
    charging_float_mode:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} charging float mode"
    timed_stored_data:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} timed stored data"
    disable_temperature_sensors:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} disable temperature sensors"
    smart_sleep_on:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} smart sleep on"
    disable_pcl_module:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} disable pcl module"
    gps_heartbeat:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} gps heartbeat"
    port_selection:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} port selection"
    special_charger:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} special charger"

binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    status_balancing:
      id: bms${bms_id}_bms_equalizing
      device_id: bms_${bms_id}
      # name: "${name} ${bms_name} status balancing"
    status_precharging:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} status precharging"
    status_charging:
      id: bms${bms_id}_charging_allowed
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} status charging"
    status_discharging:
      id: bms${bms_id}_discharging_allowed
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} status discharging"
    status_online:
      id: bms${bms_id}_online_status
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} status online"
    status_heating:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} status heating"

sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    balancing_direction:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} balancing direction"
    cell_voltage_min:
      id: bms${bms_id}_min_cell_voltage
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell voltage min"
    cell_voltage_max:
      id: bms${bms_id}_max_cell_voltage
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell voltage max"
    cell_voltage_min_cell_number:
      id: bms${bms_id}_min_voltage_cell
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell voltage min cell number"
    cell_voltage_max_cell_number:
      id: bms${bms_id}_max_voltage_cell
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell voltage max cell number"
    cell_delta_voltage:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell delta voltage"
    cell_average_voltage:
      id: bms${bms_id}_average_cell_voltage
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell average voltage"
    cell_resistance_min:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell resistance min"
    cell_resistance_max:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell resistance max"
    cell_resistance_min_cell_number:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell resistance min cell number"
    cell_resistance_max_cell_number:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell resistance max cell number"
    battery_voltage:
      id: bms${bms_id}_total_voltage
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery voltage"
    battery_current:
      id: bms${bms_id}_current
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery current"
    battery_power:
      id: bms${bms_id}_power
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery power"
    battery_power_charging:
      id: bms${bms_id}_charging_power
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery power charging"
    battery_power_discharging:
      id: bms${bms_id}_discharging_power
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery power discharging"
    temperature_sensor_1:
      id: bms${bms_id}_temperature_sensor_1
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} temperature sensor 1"
    temperature_sensor_2:
      id: bms${bms_id}_temperature_sensor_2
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} temperature sensor 2"
    temperature_sensor_3:
      id: bms${bms_id}_temperature_sensor_3
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} temperature sensor 3"
    temperature_sensor_4:
      id: bms${bms_id}_temperature_sensor_4
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} temperature sensor 4"
    temperature_sensor_5:
      id: bms${bms_id}_temperature_sensor_5
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} temperature sensor 5"
    temperature_powertube:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} temperature powertube"
    battery_capacity_state_of_charge:
      id: bms${bms_id}_state_of_charge
      device_id: bms_${bms_id}
      # name: "${name} ${bms_name} battery capacity state of charge"
    battery_capacity_remaining:
      id: bms${bms_id}_capacity_remaining_ah
      device_id: bms_${bms_id}
      # name: "${name} ${bms_name} battery capacity remaining"
    charging_cycles:
      id: bms${bms_id}_charging_cycles_raw
      device_id: bms_${bms_id}
      # name: "${name} ${bms_name} charging cycles"
    battery_capacity_total_charging_cycle:
      id: bms${bms_id}_cycle_capacity_raw
      device_id: bms_${bms_id}
      # name: "${name} ${bms_name} battery capacity total charging cycle"
    battery_total_runtime:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery total runtime"
    balancing_current:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} balancing current"
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} errors bitmask"
    cell_count_real:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell count real"
    battery_total_alarms_count:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery total alarms count"
    battery_total_alarms_active:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery total alarms active"
    uart1_protocol_number:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} uart1 protocol number"
    uart2_protocol_number:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} uart2 protocol number"
    battery_soh_valuation:
      id: bms${bms_id}_battery_soh
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery soh valuation"

text_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    errors:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} errors"
    operation_status:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} operation status"
    battery_type:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery type"
    total_runtime_formatted:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} total runtime formatted"
    info_vendorid:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} info vendorid"
    info_hardware_version:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} info hardware version"
    info_software_version:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} info software version"
    info_device_name:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} info device name"
    info_device_password:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} info device password"
    network_nodes_available:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} network nodes available"
    info_device_serial_number:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} info device serial number"
    info_device_setup_passcode:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} info device setup passcode"

number:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    cell_smart_sleep_voltage:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell smart sleep voltage"
    battery_capacity_total_settings:
      id: bms${bms_id}_battery_capacity
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} battery capacity total setting"
    cell_count_settings:
      id: bms${bms_id}_cell_count
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell count settings"
    max_charging_current:
      id: bms${bms_id}_max_charge_current
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} max charging current"
    max_discharging_current:
      id: bms${bms_id}_max_discharge_current
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} max discharging current"
    cell_overvoltage_protection:
      id: bms${bms_id}_cell_ovp
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      id: bms${bms_id}_cell_ovpr
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell overvoltage protection recovery"
    cell_balancing_trigger_voltage:
      id: bms${bms_id}_bms_balance_trigger_voltage
      device_id: bms_${bms_id}
      # name: "${name} ${bms_name} cell balancing trigger voltage"
    cell_balancing_starting_voltage:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell balancing starting voltage"
    max_balancing_current:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} max balancing current"
    cell_soc100_voltage:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell soc100 voltage"
    cell_soc0_voltage:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell soc0 voltage"
    cell_undervoltage_protection:
      id: bms${bms_id}_cell_uvp
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      id: bms${bms_id}_cell_uvpr
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell undervoltage protection recovery"
    cell_power_off_voltage:
      device_id: bms_${bms_id}
      name: "${name} ${bms_name} cell power off voltage"
