# Updated : 2026.02.01
# Version : 2.0.2
# GitHub  : https://github.com/RAR/esphome-eg4-bms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  bms_base: !include bms_base.yaml
  bms_temperature_sensor: !include bms_temperature_sensor_4.yaml
  bms_errors_bitmask: !include bms_errors_bitmask_EG4_LLV2_RS485_Modbus.yaml

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

external_components:
  - source: github://RAR/esphome-eg4-bms@v1.0.1
    refresh: 0s

eg4_bms:
  - id: eg4_bms${bms_id}
    address: ${bms_address}
    eg4_modbus_id: ${eg4_modbus_id}
    update_interval: ${bms_update_interval}

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

binary_sensor:
  # online_status
  - platform: eg4_bms
    eg4_bms_id: eg4_bms${bms_id}
    online_status:
      id: bms${bms_id}_online_status
      device_id: bms_${bms_id}
      name: "online status"
      on_state:
        then:
          - lambda: |-
              // Pass the current state to the update function
              id(global_update_fault)(${CAT_BMS}, ${bms_id}, !x);
    heating:
      device_id: bms_${bms_id}
      name: "heating"
  
  # Required sensors from component
  - platform: eg4_bms
    eg4_bms_id: eg4_bms${bms_id}
    charging:
      id: bms${bms_id}_charging_internal
      device_id: bms_${bms_id}
      internal: true
    discharging:
      id: bms${bms_id}_discharging_internal
      device_id: bms_${bms_id}
      internal: true

  # bms_switch_charging
  - platform: template
    id: bms${bms_id}_charging_allowed
    device_id: bms_${bms_id}
    name: "charging"
    lambda: |-
      return id(bms${bms_id}_charging_internal).state;

  # bms_switch_discharging
  - platform: template
    id: bms${bms_id}_discharging_allowed
    device_id: bms_${bms_id}
    name: "discharging"
    lambda: |-
      return id(bms${bms_id}_discharging_internal).state;

  # Required sensors cannot be retrieved from BMS
  # equalizing
  - platform: template
    id: bms${bms_id}_bms_equalizing
    device_id: bms_${bms_id}
    name: "balancing"
    lambda: return false;

sensor:
  - platform: eg4_bms
    eg4_bms_id: eg4_bms${bms_id}
    total_voltage:
      id: bms${bms_id}_total_voltage
      device_id: bms_${bms_id}
      name: "total voltage"
    current:
      id: bms${bms_id}_current
      device_id: bms_${bms_id}
      name: "current"
    power:
      id: bms${bms_id}_power
      device_id: bms_${bms_id}
      name: "power"
    charging_power:
      id: bms${bms_id}_charging_power
      device_id: bms_${bms_id}
      name: "charging power"
    discharging_power:
      id: bms${bms_id}_discharging_power
      device_id: bms_${bms_id}
      name: "discharging power"
    remaining_capacity:
      id: bms${bms_id}_capacity_remaining_ah
      device_id: bms_${bms_id}
      name: "remaining capacity"
    full_capacity:
      id: bms${bms_id}_battery_capacity
      device_id: bms_${bms_id}
      name: "total capacity"
    state_of_charge:
      id: bms${bms_id}_state_of_charge
      device_id: bms_${bms_id}
      name: "state of charge"
    state_of_health:
      id: bms${bms_id}_battery_soh
      device_id: bms_${bms_id}
      name: "state of health"
    cycle_count:
      id: bms${bms_id}_charging_cycles_raw
      device_id: bms_${bms_id}
      name: "cycle"
    max_charge_current:
      id: bms${bms_id}_max_charge_current
      device_id: bms_${bms_id}
      name: "max charging current"
    min_cell_voltage:
      id: bms${bms_id}_min_cell_voltage
      device_id: bms_${bms_id}
      name: "min cell voltage"
    max_cell_voltage:
      id: bms${bms_id}_max_cell_voltage
      device_id: bms_${bms_id}
      name: "max cell voltage"
    delta_cell_voltage:
      id: bms${bms_id}_delta_cell_voltage
      device_id: bms_${bms_id}
      name: "delta cell voltage"
    cell_average_voltage:
      id: bms${bms_id}_cell_average_voltage
      device_id: bms_${bms_id}
      name: "cell average voltage"
    cell_voltage_1:
      id: bms${bms_id}_cell_voltage_1
      device_id: bms_${bms_id}
      name: "cell voltage 01"
    cell_voltage_2:
      id: bms${bms_id}_cell_voltage_2
      device_id: bms_${bms_id}
      name: "cell voltage 02"
    cell_voltage_3:
      id: bms${bms_id}_cell_voltage_3
      device_id: bms_${bms_id}
      name: "cell voltage 03"
    cell_voltage_4:
      id: bms${bms_id}_cell_voltage_4
      device_id: bms_${bms_id}
      name: "cell voltage 04"
    cell_voltage_5:
      id: bms${bms_id}_cell_voltage_5
      device_id: bms_${bms_id}
      name: "cell voltage 05"
    cell_voltage_6:
      id: bms${bms_id}_cell_voltage_6
      device_id: bms_${bms_id}
      name: "cell voltage 06"
    cell_voltage_7:
      id: bms${bms_id}_cell_voltage_7
      device_id: bms_${bms_id}
      name: "cell voltage 07"
    cell_voltage_8:
      id: bms${bms_id}_cell_voltage_8
      device_id: bms_${bms_id}
      name: "cell voltage 08"
    cell_voltage_9:
      id: bms${bms_id}_cell_voltage_9
      device_id: bms_${bms_id}
      name: "cell voltage 09"
    cell_voltage_10:
      id: bms${bms_id}_cell_voltage_10
      device_id: bms_${bms_id}
      name: "cell voltage 10"
    cell_voltage_11:
      id: bms${bms_id}_cell_voltage_11
      device_id: bms_${bms_id}
      name: "cell voltage 11"
    cell_voltage_12:
      id: bms${bms_id}_cell_voltage_12
      device_id: bms_${bms_id}
      name: "cell voltage 12"
    cell_voltage_13:
      id: bms${bms_id}_cell_voltage_13
      device_id: bms_${bms_id}
      name: "cell voltage 13"
    cell_voltage_14:
      id: bms${bms_id}_cell_voltage_14
      device_id: bms_${bms_id}
      name: "cell voltage 14"
    cell_voltage_15:
      id: bms${bms_id}_cell_voltage_15
      device_id: bms_${bms_id}
      name: "cell voltage 15"
    cell_voltage_16:
      id: bms${bms_id}_cell_voltage_16
      device_id: bms_${bms_id}
      name: "cell voltage 16"
    temperature_1:
      id: bms${bms_id}_temperature_sensor_1
      device_id: bms_${bms_id}
      name: "cell temperature 1"
    temperature_2:
      id: bms${bms_id}_temperature_sensor_2
      device_id: bms_${bms_id}
      name: "cell temperature 2"
    temperature_3:
      id: bms${bms_id}_temperature_sensor_3
      device_id: bms_${bms_id}
      name: "cell temperature 3"
    temperature_4:
      id: bms${bms_id}_temperature_sensor_4
      device_id: bms_${bms_id}
      name: "cell temperature 4"
    pcb_temperature:
      device_id: bms_${bms_id}
      name: "mosfet temperature"
    avg_temperature:
      device_id: bms_${bms_id}
      name: "average cell temperature"
    max_temperature:
      device_id: bms_${bms_id}
      name: "max cell temperature"
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      device_id: bms_${bms_id}
      name: "errors bitmask"
    warnings_bitmask:
      id: bms${bms_id}_warnings_bitmask
      device_id: bms_${bms_id}
      name: "warnings bitmask"
    protection_bitmask:
      id: bms${bms_id}_protection_bitmask
      device_id: bms_${bms_id}
      name: "protection bitmask"
    min_voltage_cell:
      id: bms${bms_id}_min_voltage_cell
      name: "min voltage cell"
      device_id: bms_${bms_id}
    max_voltage_cell:
      id: bms${bms_id}_max_voltage_cell
      device_id: bms_${bms_id}
      name: "max voltage cell"

  # Required sensors cannot be retrieved from BMS
  - platform: template
    id: bms${bms_id}_bms_balance_trigger_voltage
    device_id: bms_${bms_id}
    name: "balance trigger voltage"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: "V"
    state_class: measurement
    device_class: 'voltage'
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return 0.030;

  - platform: template
    id: bms${bms_id}_cell_ovp
    device_id: bms_${bms_id}
    name: "cell ovp"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: "V"
    state_class: measurement
    device_class: 'voltage'
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return 3.650;

  - platform: template
    id: bms${bms_id}_cell_uvp
    device_id: bms_${bms_id}
    name: "cell uvp"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 3
    unit_of_measurement: "V"
    state_class: measurement
    device_class: 'voltage'
    filters:
      - or:
        - throttle: 10s
        - delta: 0.001
    lambda: return 2.500;

  - platform: template
    id: bms${bms_id}_max_discharge_current
    device_id: bms_${bms_id}
    name: "max discharge current"
    update_interval: ${bms_update_interval}
    accuracy_decimals: 0
    unit_of_measurement: "A"
    state_class: measurement
    device_class: 'current'
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return 200;

  # Charging cycle capacity - Calculated from charging cycles and battery capacity
  - platform: template
    id: bms${bms_id}_cycle_capacity_raw
    device_id: bms_${bms_id}
    name: "charging cycle capacity"
    update_interval: ${bms_update_interval}
    unit_of_measurement: Ah
    state_class: total
    icon: mdi:car-battery
    accuracy_decimals: 0
    internal: true
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: return id(bms${bms_id}_charging_cycles_raw).state * id(bms${bms_id}_battery_capacity).state;

text_sensor:
  - platform: eg4_bms
    eg4_bms_id: eg4_bms${bms_id}
    status:
      id: bms${bms_id}_status
      device_id: bms_${bms_id}
      name: "status"
    warnings:
      id: bms${bms_id}_warnings_text
      device_id: bms_${bms_id}
      name: "warnings"
    protection:
      id: bms${bms_id}_protection_text
      device_id: bms_${bms_id}
      name: "protection"
    error:
      id: bms${bms_id}_errors_text
      device_id: bms_${bms_id}
      name: "errors"
    model:
      device_id: bms_${bms_id}
      name: "model"
    firmware_version:
      device_id: bms_${bms_id}
      name: "version"
    serial_number:
      device_id: bms_${bms_id}
      name: "firmware date"
