# Updated : 2026.01.19
# Version : 1.0.0
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# PACE BMS specific version - passes through SOC/capacity directly and
# converts mV voltage thresholds to V for YamBMS compatibility

sensor:
  # +--------------------------------------+
  # | Battery State of Charge (SOC)        |
  # +--------------------------------------+
  - platform: template
    name: "Battery SoC"
    id: bms${bms_id}_battery_soc
    device_id: bms_${bms_id}
    update_interval: ${bms_update_interval}
    unit_of_measurement: "%"
    device_class: battery
    accuracy_decimals: 0
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: |-
      // PACE BMS reports SOC directly as percentage - use it as-is
      return id(bms${bms_id}_state_of_charge).state;

  # +--------------------------------------+
  # | Battery Capacity Remaining           |
  # +--------------------------------------+
  - platform: template
    name: "Battery Capacity Remaining"
    id: bms${bms_id}_battery_capacity_remaining
    device_id: bms_${bms_id}
    update_interval: ${bms_update_interval}
    unit_of_measurement: Ah
    state_class: measurement
    icon: mdi:car-battery
    accuracy_decimals: 0
    filters:
      - or:
        - throttle: 10s
        - delta: 1
    lambda: |-
      // PACE BMS reports capacity remaining directly - use it as-is
      return id(bms${bms_id}_capacity_remaining_ah).state;

  # +--------------------------------------+
  # | Voltage threshold wrappers (mV to V) |
  # +--------------------------------------+
  # PACE BMS reports these in mV, YamBMS expects V
  # Note: balance_trigger_voltage is handled in bms_base_balancer_PACE.yaml
  
  # Cell UVP wrapper - converts mV to V
  - platform: template
    id: bms${bms_id}_cell_uvp
    device_id: bms_${bms_id}
    update_interval: ${bms_update_interval}
    unit_of_measurement: V
    device_class: voltage
    accuracy_decimals: 3
    lambda: |-
      // Convert PACE cell_uvp from mV to V
      return id(bms${bms_id}_cell_uvp_mv).state * 0.001;

  # Cell OVP wrapper - converts mV to V
  - platform: template
    id: bms${bms_id}_cell_ovp
    device_id: bms_${bms_id}
    update_interval: ${bms_update_interval}
    unit_of_measurement: V
    device_class: voltage
    accuracy_decimals: 3
    lambda: |-
      // Convert PACE cell_ovp from mV to V
      return id(bms${bms_id}_cell_ovp_mv).state * 0.001;
