# Updated : 2025.12.23
# Version : 1.0.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# +--------------------------------------+
# | BMS Modbus TCP Client Package        |
# +--------------------------------------+
#
# PURPOSE:
#   Master node that polls BMS servers over network
#   Combines data from multiple servers and controls inverter
#
# CURRENT LIMITATION:
#   ESPHome does not have native Modbus TCP client support yet
#   (Feature request: https://github.com/esphome/feature-requests/issues/708)
#
# SOLUTION:
#   Use hardware TCP-to-Modbus bridge between ESP32 and network
#
# +--------------------------------------+
# | Hardware Bridge Approach             |
# +--------------------------------------+
#
# ARCHITECTURE:
#   ESP32 → Modbus RTU → Hardware Bridge → Network (TCP) → Server Nodes
#
# The hardware bridge translates between:
#   - Local: Modbus RTU (what ESP32 speaks)
#   - Network: Modbus TCP (what servers expose)
#
# REQUIRED HARDWARE:
#   - ESP32 (for YamBMS master logic)
#   - Hardware TCP-to-Modbus bridge ($30-100):
#     * EBYTE NT1 (~$40) - recommended
#     * USR-TCP232-410S (~$30)
#     * Elfin-EE11 (~$50)
#
# BRIDGE CONFIGURATION:
#   The bridge maps Modbus addresses to server IPs:
#     Address 1 → 192.168.1.101:502 (Server 1)
#     Address 2 → 192.168.1.102:502 (Server 2)
#     Address 3 → 192.168.1.103:502 (Server 3)
#
# ESP32 CODE:
#   Uses standard Modbus client - no changes needed!
#   The bridge handles all TCP communication transparently.

# +--------------------------------------+
# | Configuration                        |
# +--------------------------------------+

# Use standard Modbus client package (works via bridge)
packages:
  modbus_client: !include bms_combine_modbus_client.yaml

# Network monitoring
binary_sensor:
  - platform: template
    id: modbus_tcp_network_active
    name: "${name} Network Active"
    icon: "mdi:network"
    entity_category: diagnostic
    lambda: |-
      return id(my_network).is_connected();

sensor:
  - platform: wifi_signal
    id: client_wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      id: client_ip_address
      name: "${name} IP Address"
      icon: "mdi:ip-network"
      entity_category: diagnostic

# +--------------------------------------+
# | Setup Instructions                   |
# +--------------------------------------+
#
# STEP 1: Configure Hardware Bridge
#   - Connect bridge to network
#   - Access bridge web interface
#   - Set mode: "Modbus TCP Client"
#   - Add server mappings:
#     Addr 1 → <server1-ip>:502
#     Addr 2 → <server2-ip>:502
#     Addr 3 → <server3-ip>:502
#
# STEP 2: Wire ESP32 to Bridge
#   - ESP32 TX → Bridge RX
#   - ESP32 RX → Bridge TX
#   - Configure UART in main YAML
#
# STEP 3: Configure ESP32
#   - Use standard Modbus client packages
#   - Poll with bms_id: '1', '2', '3', etc.
#   - Bridge forwards to corresponding server IPs
#
# TESTING:
#   1. Verify servers accessible: ping <server-ip>
#   2. Test server port: nc -zv <server-ip> 502
#   3. Check bridge can connect to servers
#   4. Monitor ESP32 logs for BMS data
#
# +--------------------------------------+
# | Alternative: MQTT (Recommended)      |
# +--------------------------------------+
#
# For a bridge-free solution, consider MQTT instead:
#   - No hardware bridge needed
#   - Native ESPHome support
#   - More efficient (push vs poll)
#   - See: YamBMS_MQTT_vs_ModbusTCP_analysis.md
#
# +--------------------------------------+
# | Future: Native TCP Client            |
# +--------------------------------------+
#
# When ESPHome adds native Modbus TCP client:
#   - No hardware bridge needed
#   - Direct ESP32 → Network → Servers
#   - Watch: https://github.com/esphome/feature-requests/issues/708
