# Updated : 2026.02.01
# Version : 1.3.5
# GitHub  : https://github.com/txubelaxu/esphome-jk-bms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  bms_base: !include bms_base.yaml
  bms_temperature_sensor: !include bms_temperature_sensor_5.yaml
  bms_errors_bitmask: !include bms_errors_bitmask_JK_RS485_Modbus.yaml

# +--------------------------------------+
# | Component settings                   |
# +--------------------------------------+

jk_rs485_bms:
  - id: jk_rs485_bms${bms_id}
    rs485_address: ${bms_address}
    jk_rs485_sniffer_id: ${sniffer_id}
    update_interval: ${bms_update_interval}

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

switch:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    precharging:
      device_id: bms_${bms_id}
      name: "precharging"
    charging:
      id: bms${bms_id}_charge_switch
      device_id: bms_${bms_id}
      name: "charging"
    discharging:
      id: bms${bms_id}_discharge_switch
      device_id: bms_${bms_id}
      name: "discharging"
    balancing:
      id: bms${bms_id}_balance_switch
      device_id: bms_${bms_id}
      name: "balancing"
    emergency:
      device_id: bms_${bms_id}
      name: "emergency"
    heating:
      device_id: bms_${bms_id}
      name: "heating"
    display_always_on:
      device_id: bms_${bms_id}
      name: "display_always_on"
    charging_float_mode:
      device_id: bms_${bms_id}
      name: "charging float mode"
    timed_stored_data:
      device_id: bms_${bms_id}
      name: "timed stored data"
    disable_temperature_sensors:
      device_id: bms_${bms_id}
      name: "disable temperature sensors"
    smart_sleep_on:
      device_id: bms_${bms_id}
      name: "smart sleep on"
    disable_pcl_module:
      device_id: bms_${bms_id}
      name: "disable pcl module"
    gps_heartbeat:
      device_id: bms_${bms_id}
      name: "gps heartbeat"
    port_selection:
      device_id: bms_${bms_id}
      name: "port selection"
    special_charger:
      device_id: bms_${bms_id}
      name: "special charger"

binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    status_balancing:
      id: bms${bms_id}_bms_equalizing
      device_id: bms_${bms_id}
      # name: "status balancing"
    status_precharging:
      device_id: bms_${bms_id}
      name: "status precharging"
    status_charging:
      id: bms${bms_id}_charging_allowed
      device_id: bms_${bms_id}
      name: "status charging"
    status_discharging:
      id: bms${bms_id}_discharging_allowed
      device_id: bms_${bms_id}
      name: "status discharging"
    status_online:
      id: bms${bms_id}_online_status
      device_id: bms_${bms_id}
      name: "status online"
      on_state:
        then:
          - lambda: |-
              // Pass the current state to the update function
              id(global_update_fault)(${CAT_BMS}, ${bms_id}, !x);
    status_heating:
      device_id: bms_${bms_id}
      name: "status heating"

sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    balancing_direction:
      device_id: bms_${bms_id}
      name: "balancing direction"
    cell_voltage_min:
      id: bms${bms_id}_min_cell_voltage
      device_id: bms_${bms_id}
      name: "cell voltage min"
    cell_voltage_max:
      id: bms${bms_id}_max_cell_voltage
      device_id: bms_${bms_id}
      name: "cell voltage max"
    cell_voltage_min_cell_number:
      id: bms${bms_id}_min_voltage_cell
      device_id: bms_${bms_id}
      name: "cell voltage min cell number"
    cell_voltage_max_cell_number:
      id: bms${bms_id}_max_voltage_cell
      device_id: bms_${bms_id}
      name: "cell voltage max cell number"
    cell_delta_voltage:
      device_id: bms_${bms_id}
      name: "cell delta voltage"
    cell_average_voltage:
      id: bms${bms_id}_average_cell_voltage
      device_id: bms_${bms_id}
      name: "cell average voltage"
    cell_resistance_min:
      device_id: bms_${bms_id}
      name: "cell resistance min"
    cell_resistance_max:
      device_id: bms_${bms_id}
      name: "cell resistance max"
    cell_resistance_min_cell_number:
      device_id: bms_${bms_id}
      name: "cell resistance min cell number"
    cell_resistance_max_cell_number:
      device_id: bms_${bms_id}
      name: "cell resistance max cell number"
    battery_voltage:
      id: bms${bms_id}_total_voltage
      device_id: bms_${bms_id}
      name: "battery voltage"
    battery_current:
      id: bms${bms_id}_current
      device_id: bms_${bms_id}
      name: "battery current"
    battery_power:
      id: bms${bms_id}_power
      device_id: bms_${bms_id}
      name: "battery power"
    battery_power_charging:
      id: bms${bms_id}_charging_power
      device_id: bms_${bms_id}
      name: "battery power charging"
    battery_power_discharging:
      id: bms${bms_id}_discharging_power
      device_id: bms_${bms_id}
      name: "battery power discharging"
    temperature_sensor_1:
      id: bms${bms_id}_temperature_sensor_1
      device_id: bms_${bms_id}
      name: "temperature sensor 1"
    temperature_sensor_2:
      id: bms${bms_id}_temperature_sensor_2
      device_id: bms_${bms_id}
      name: "temperature sensor 2"
    temperature_sensor_3:
      id: bms${bms_id}_temperature_sensor_3
      device_id: bms_${bms_id}
      name: "temperature sensor 3"
    temperature_sensor_4:
      id: bms${bms_id}_temperature_sensor_4
      device_id: bms_${bms_id}
      name: "temperature sensor 4"
    temperature_sensor_5:
      id: bms${bms_id}_temperature_sensor_5
      device_id: bms_${bms_id}
      name: "temperature sensor 5"
    temperature_powertube:
      device_id: bms_${bms_id}
      name: "temperature powertube"
    battery_capacity_state_of_charge:
      id: bms${bms_id}_state_of_charge
      device_id: bms_${bms_id}
      # name: "battery capacity state of charge"
    battery_capacity_remaining:
      id: bms${bms_id}_capacity_remaining_ah
      device_id: bms_${bms_id}
      # name: "battery capacity remaining"
    charging_cycles:
      id: bms${bms_id}_charging_cycles_raw
      device_id: bms_${bms_id}
      # name: "charging cycles"
    battery_capacity_total_charging_cycle:
      id: bms${bms_id}_cycle_capacity_raw
      device_id: bms_${bms_id}
      # name: "battery capacity total charging cycle"
    battery_total_runtime:
      device_id: bms_${bms_id}
      name: "battery total runtime"
    balancing_current:
      device_id: bms_${bms_id}
      name: "balancing current"
    errors_bitmask:
      id: bms${bms_id}_errors_bitmask
      device_id: bms_${bms_id}
      name: "errors bitmask"
    cell_count_real:
      device_id: bms_${bms_id}
      name: "cell count real"
    battery_total_alarms_count:
      device_id: bms_${bms_id}
      name: "battery total alarms count"
    battery_total_alarms_active:
      device_id: bms_${bms_id}
      name: "battery total alarms active"
    uart1_protocol_number:
      device_id: bms_${bms_id}
      name: "uart1 protocol number"
    uart2_protocol_number:
      device_id: bms_${bms_id}
      name: "uart2 protocol number"
    battery_soh_valuation:
      id: bms${bms_id}_battery_soh
      device_id: bms_${bms_id}
      name: "battery soh valuation"
    cell_voltage_01:
      device_id: bms_${bms_id}
      name: "cell voltage 01"
    cell_voltage_02:
      device_id: bms_${bms_id}
      name: "cell voltage 02"
    cell_voltage_03:
      device_id: bms_${bms_id}
      name: "cell voltage 03"
    cell_voltage_04:
      device_id: bms_${bms_id}
      name: "cell voltage 04"
    cell_voltage_05:
      device_id: bms_${bms_id}
      name: "cell voltage 05"
    cell_voltage_06:
      device_id: bms_${bms_id}
      name: "cell voltage 06"
    cell_voltage_07:
      device_id: bms_${bms_id}
      name: "cell voltage 07"
    cell_voltage_08:
      device_id: bms_${bms_id}
      name: "cell voltage 08"
    cell_voltage_09:
      device_id: bms_${bms_id}
      name: "cell voltage 09"
    cell_voltage_10:
      device_id: bms_${bms_id}
      name: "cell voltage 10"
    cell_voltage_11:
      device_id: bms_${bms_id}
      name: "cell voltage 11"
    cell_voltage_12:
      device_id: bms_${bms_id}
      name: "cell voltage 12"
    cell_voltage_13:
      device_id: bms_${bms_id}
      name: "cell voltage 13"
    cell_voltage_14:
      device_id: bms_${bms_id}
      name: "cell voltage 14"
    cell_voltage_15:
      device_id: bms_${bms_id}
      name: "cell voltage 15"
    cell_voltage_16:
      device_id: bms_${bms_id}
      name: "cell voltage 16"
    # cell_voltage_17:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 17"
    # cell_voltage_18:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 18"
    # cell_voltage_19:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 19"
    # cell_voltage_20:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 20"
    # cell_voltage_21:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 21"
    # cell_voltage_22:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 22"
    # cell_voltage_23:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 23"
    # cell_voltage_24:
    #   device_id: bms_${bms_id}
    #   name: "cell voltage 24"
    cell_resistance_01:
      device_id: bms_${bms_id}
      name: "cell resistance 01"
    cell_resistance_02:
      device_id: bms_${bms_id}
      name: "cell resistance 02"
    cell_resistance_03:
      device_id: bms_${bms_id}
      name: "cell resistance 03"
    cell_resistance_04:
      device_id: bms_${bms_id}
      name: "cell resistance 04"
    cell_resistance_05:
      device_id: bms_${bms_id}
      name: "cell resistance 05"
    cell_resistance_06:
      device_id: bms_${bms_id}
      name: "cell resistance 06"
    cell_resistance_07:
      device_id: bms_${bms_id}
      name: "cell resistance 07"
    cell_resistance_08:
      device_id: bms_${bms_id}
      name: "cell resistance 08"
    cell_resistance_09:
      device_id: bms_${bms_id}
      name: "cell resistance 09"
    cell_resistance_10:
      device_id: bms_${bms_id}
      name: "cell resistance 10"
    cell_resistance_11:
      device_id: bms_${bms_id}
      name: "cell resistance 11"
    cell_resistance_12:
      device_id: bms_${bms_id}
      name: "cell resistance 12"
    cell_resistance_13:
      device_id: bms_${bms_id}
      name: "cell resistance 13"
    cell_resistance_14:
      device_id: bms_${bms_id}
      name: "cell resistance 14"
    cell_resistance_15:
      device_id: bms_${bms_id}
      name: "cell resistance 15"
    cell_resistance_16:
      device_id: bms_${bms_id}
      name: "cell resistance 16"
    # cell_resistance_17:
    #   device_id: bms_${bms_id}
    #   name: "cell resistance 17"
    # cell_resistance_18:
    #   device_id: bms_${bms_id}
    #   name: "cell resistance 18"
    # cell_resistance_19:
    #   device_id: bms_${bms_id}
    #   name: "cell resistance 19"
    # cell_resistance_20:
    #   device_id: bms_${bms_id}
    #   name: "cell resistance 20"
    # cell_resistance_21:
    #   device_id: bms_${bms_id}
    #   name: "cell resistance 21"
    # cell_resistance_22:
    #   device_id: bms_${bms_id}
    #   name: "cell resistance 22"
    # cell_resistance_23:
    #   device_id: bms_${bms_id}
    #   name: "cell resistance 23"
    # cell_resistance_24:
    #   device_id: bms_${bms_id}
    #   name: "cell resistance 24"

text_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    errors:
      device_id: bms_${bms_id}
      name: "errors"
    operation_status:
      device_id: bms_${bms_id}
      name: "operation status"
    battery_type:
      device_id: bms_${bms_id}
      name: "battery type"
    total_runtime_formatted:
      device_id: bms_${bms_id}
      name: "total runtime formatted"
    info_vendorid:
      device_id: bms_${bms_id}
      name: "info vendorid"
    info_hardware_version:
      device_id: bms_${bms_id}
      name: "info hardware version"
    info_software_version:
      device_id: bms_${bms_id}
      name: "info software version"
    info_device_name:
      device_id: bms_${bms_id}
      name: "info device name"
    info_device_password:
      device_id: bms_${bms_id}
      name: "info device password"
    network_nodes_available:
      device_id: bms_${bms_id}
      name: "network nodes available"
    info_device_serial_number:
      device_id: bms_${bms_id}
      name: "info device serial number"
    info_device_setup_passcode:
      device_id: bms_${bms_id}
      name: "info device setup passcode"

number:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: jk_rs485_bms${bms_id}
    cell_smart_sleep_voltage:
      device_id: bms_${bms_id}
      name: "cell smart sleep voltage"
    battery_capacity_total_settings:
      id: bms${bms_id}_battery_capacity
      device_id: bms_${bms_id}
      name: "battery capacity total setting"
    cell_count_settings:
      id: bms${bms_id}_cell_count
      device_id: bms_${bms_id}
      name: "cell count settings"
    max_charging_current:
      id: bms${bms_id}_max_charge_current
      device_id: bms_${bms_id}
      name: "max charging current"
    max_discharging_current:
      id: bms${bms_id}_max_discharge_current
      device_id: bms_${bms_id}
      name: "max discharging current"
    cell_overvoltage_protection:
      id: bms${bms_id}_cell_ovp
      device_id: bms_${bms_id}
      name: "cell overvoltage protection"
    cell_overvoltage_protection_recovery:
      id: bms${bms_id}_cell_ovpr
      device_id: bms_${bms_id}
      name: "cell overvoltage protection recovery"
    cell_balancing_trigger_voltage:
      id: bms${bms_id}_bms_balance_trigger_voltage
      device_id: bms_${bms_id}
      name: "cell balancing trigger voltage"
    cell_balancing_starting_voltage:
      device_id: bms_${bms_id}
      name: "cell balancing starting voltage"
    max_balancing_current:
      device_id: bms_${bms_id}
      name: "max balancing current"
    cell_soc100_voltage:
      device_id: bms_${bms_id}
      name: "cell soc100 voltage"
    cell_soc0_voltage:
      device_id: bms_${bms_id}
      name: "cell soc0 voltage"
    cell_undervoltage_protection:
      id: bms${bms_id}_cell_uvp
      device_id: bms_${bms_id}
      name: "cell undervoltage protection"
    cell_undervoltage_protection_recovery:
      id: bms${bms_id}_cell_uvpr
      device_id: bms_${bms_id}
      name: "cell undervoltage protection recovery"
    cell_power_off_voltage:
      device_id: bms_${bms_id}
      name: "cell power off voltage"
