# Updated : 2026.01.29
# Version : 1.1.6
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# https://wiki.lilygo.cc/get_started/en/High_speed/T-Connect/T-Connect.html

substitutions:
  board_chip: "ESP32-S3"
  board_name: "LilyGo T-Connect"
  # Interfaces GPIOs
  # uart_esp_1
  tx_pin_1: "4"
  rx_pin_1: "5"
  # uart_esp_2
  tx_pin_2: "6"
  rx_pin_2: "7"
  # uart_esp_3
  tx_pin_3: "17"
  rx_pin_3: "18"
  # canbus_esp32_can
  tx_pin_4: "9"
  rx_pin_4: "10"
  # canbus_mcp2515
  spi_mosi_pin: "11"
  spi_miso_pin: "13"
  spi_clk_pin: "12"
  mcp2515_cs_pin: "14"
  # Requirement: RGB flag to show functionality is available
  board_has_rgb: "true"

packages:
  device_base: !include ../base/device_base.yaml
  device_base_wifi: !include ../base/device_base_wifi.yaml
  #board_rgb_led: !include board_options_rgb_led_status.yaml

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB # adjust according to your ESP32-S3 version
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  reboot_timeout: 0s

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"
  hardware_uart: USB_SERIAL_JTAG

# SPI for LED strip APA102
spi:
  - id: lilygo_spi_bus
    clk_pin: 3
    mosi_pin: 8

light:
  # https://esphome.io/components/light/spi_led_strip.html
  # ESP Light used to see the inverter heartbeat
  # LilyGo T-Connect: APA102 chip - using spi library, 4 leds, data-IO8, clock-IO3

  # All leds (Targeted if user wants all LEDs to flash)
  # Target ID: esp_light
  - platform: spi_led_strip
    spi_id: lilygo_spi_bus
    id: esp_light
    num_leds: 4
    data_rate: 1MHz
    internal: true
    default_transition_length: 0ms

  # Individual leds (Targeted if user wants a specific LED)
  # Target IDs: led_1, led_2, led_3, led_4
  - platform: partition
    id: led_1
    default_transition_length: 0ms
    segments:
      - id: esp_light
        from: 0
        to: 0

  - platform: partition
    id: led_2
    default_transition_length: 0ms
    segments:
      - id: esp_light
        from: 1
        to: 1

  - platform: partition
    id: led_3
    default_transition_length: 0ms
    segments:
      - id: esp_light
        from: 2
        to: 2

  - platform: partition
    id: led_4
    default_transition_length: 0ms
    segments:
      - id: esp_light
        from: 3
        to: 3
