# Updated : 2025.12.23
# Version : 1.0.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# +--------------------------------------+
# | Modbus TCP Bridge Configuration      |
# +--------------------------------------+
#
# PURPOSE:
#   Exposes BMS data over network via Modbus TCP (port 502)
#   Replaces RS485 bus for inter-node communication
#
# WHAT THIS DOES:
#   - Listens on TCP port 502 (standard Modbus TCP)
#   - Allows remote nodes to read BMS data over WiFi/Ethernet
#   - No RS485 bus wiring needed between nodes!
#
# USAGE:
#   - Include in server nodes (BMS monitoring nodes)
#   - Each server gets unique IP address
#   - Master node connects via network instead of RS485 bus

# Configuration
substitutions:
  # TCP Bridge Settings
  modbus_tcp_port: '502'                      # Standard Modbus TCP port
  modbus_tcp_allowed_clients: '5'             # Max concurrent connections
  modbus_tcp_client_timeout: '60s'            # Idle client timeout
  # Internal Modbus Settings (used by bridge internally)
  modbus_id: 'modbus_1'
  modbus_baud_rate: '19200'
  modbus_send_wait_time: '250ms'
  modbus_rtu_response_timeout: '3000ms'
  modbus_crc_bytes_swapped: 'false'

# External component for TCP bridge functionality
external_components:
  - source: github://rosenrot00/esphome_modbus_bridge@main
    components: [ modbus_bridge ]
    refresh: 1d

# Internal: UART for local BMS communication
# (This is NOT for inter-node communication - that's now TCP!)
uart:
  - id: !extend ${modbus_uart_id}
    baud_rate: ${modbus_baud_rate}

# Internal: Modbus RTU server for local BMS
modbus:
  - uart_id: ${modbus_uart_id}
    id: ${modbus_id}
    role: ${modbus_role}
    send_wait_time: ${modbus_send_wait_time}

# TCP Bridge: Exposes Modbus over network
modbus_bridge:
  uart_id: ${modbus_uart_id}
  tcp_port: ${modbus_tcp_port}
  tcp_allowed_clients: ${modbus_tcp_allowed_clients}
  tcp_client_timeout: ${modbus_tcp_client_timeout}
  rtu_response_timeout: ${modbus_rtu_response_timeout}
  crc_bytes_swapped: ${modbus_crc_bytes_swapped}
  # Event triggers
  on_tcp_clients:
    - logger.log:
        format: "TCP clients connected: %d"
        args: ['x']
  on_rtu_send:
    - logger.log: "Reading BMS data"
  on_rtu_receive:
    - logger.log: "BMS data received"
  on_rtu_timeout:
    - logger.log:
        format: "BMS timeout (check local BMS connection)"
        level: WARN

# Network monitoring
binary_sensor:
  - platform: template
    id: modbus_tcp_bridge_active
    name: "${name} TCP Bridge Active"
    icon: "mdi:bridge"
    entity_category: diagnostic
    lambda: |-
      return id(my_network).is_connected();

sensor:
  - platform: wifi_signal
    id: wifi_signal_strength
    name: "${name} WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic
    internal: false

text_sensor:
  - platform: wifi_info
    ip_address:
      id: wifi_ip_address
      name: "${name} IP Address"
      icon: "mdi:ip-network"
      entity_category: diagnostic

# +--------------------------------------+
# | How This Works                       |
# +--------------------------------------+
#
# NETWORK EXPOSURE:
#   This node exposes BMS data on: <node-ip>:502
#   Master node connects via network (WiFi/Ethernet)
#   No RS485 bus wiring needed between nodes!
#
# CONNECTION INFO:
#   - Protocol: Modbus TCP (standard)
#   - Port: 502
#   - Max clients: 5 concurrent connections
#   - Data: All 33+ BMS registers
#
# SETUP CHECKLIST:
#   □ Configure WiFi or Ethernet
#   □ Note the IP address (check wifi_ip_address sensor)
#   □ Verify port 502 accessible (firewall)
#   □ Test connection: nc -zv <ip> 502
#
# ADVANTAGES VS RS485 BUS:
#   ✓ No distance limits (network reach)
#   ✓ No RS485 wiring between nodes
#   ✓ Easy to add/remove nodes
#   ✓ Uses existing network infrastructure
#   ✓ Works across VLANs/subnets
