# Updated : 2025.09.12
# Version : 1.1.4
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# The settings below can be changed via `vars` when importing the package
# or by declaring new `substitutions` in the main YAML.
substitutions:
  mcp2515_canbus_id: '2'
  mcp2515_canbus_bitrate: '500kbps'

spi:
  - id: mcp2515_spi
    mosi_pin: ${spi_mosi_pin}
    miso_pin: ${spi_miso_pin}
    clk_pin: ${spi_clk_pin}
    interface: spi3

canbus:
  - platform: mcp2515
    spi_id: mcp2515_spi
    id: ${canbus_node_id}
    cs_pin: ${mcp2515_cs_pin}
    can_id: ${mcp2515_canbus_id}
    bit_rate: ${mcp2515_canbus_bitrate}
