# Updated : 2026.02.03
# Version : 1.1.3
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.


substitutions:
  enable_led_logging: 'false'
  global_status_led: "esp_light"

globals:
  # 2D grid of physical LED pointers
  # Structure: [Component Category (0-15)] -> [Specific Instance ID (0-N)]
  - id: global_led_registry
    type: std::vector<std::vector<esphome::light::LightState*>>
    initial_value: 'std::vector<std::vector<esphome::light::LightState*>>(16)'

  # ---------------------------------------------------------
  # Global Function: Update LED assignment
  # ---------------------------------------------------------
  - id: global_register_led
    type: std::function<void(int, int, light::LightState*)>
    initial_value: |-
      [](int category, int instance, light::LightState* led) {

        if (led == &id(virtual_status_light)) {
            led = nullptr; 
        }

        int computer_instance = instance - 1;
        if (category < 0 || category >= 16 || computer_instance < 0) return;

        auto &leds = id(global_led_registry)[category];
        auto &faults = id(global_instance_faults)[category];

        if (leds.size() <= computer_instance) {
          leds.resize(computer_instance + 1, nullptr);
          faults.resize(computer_instance + 1, false);
        }
        leds[computer_instance] = led;
      }


output:
  - platform: template
    id: virtual_output
    type: binary
    write_action: []

# Fake light to act as a placeholder for LED control logic
light:
  - platform: binary
    id: virtual_status_light
    output: virtual_output


interval:
  - interval: 50ms
    then:
      - lambda: |-
          // -----------------------------------------------------------------------
          // CONFIGURATION CONSTANTS
          // -----------------------------------------------------------------------
          // Define the timing characteristics of the annunciator signal.
          const uint32_t HEADER_MS = 1000;        // Duration of the initial Blue/Green sync pulse
          const uint32_t PRE_PIP_GAP_MS = 500;    // Silence between Header and first Red Pip
          const uint32_t PIP_DURATION_MS = 300;   // Total time per pip (150ms ON / 150ms OFF)
          const uint32_t GROUP_GAP_MS = 500;      // Extended pause inserted after every 4th pip
          const uint32_t END_PADDING_MS = 1000;   // Minimum silence at end of cycle before restart
          
          // -----------------------------------------------------------------------
          // STATE MANAGEMENT
          // -----------------------------------------------------------------------
          // Tracks the current fault index for LEDs with multiple assigned faults
          struct LedStateContext {
              size_t fault_index;     // Index in the local list of active faults
              int last_cycle_id;      // Used to detect when a new global cycle begins
          };

          // Persistent storage for LED states (Key: LightState pointer)
          static std::map<esphome::light::LightState*, LedStateContext> states;
          
          // Global timing variables
          static uint32_t cycle_start_ms = 0;
          static uint32_t current_cycle_duration = 2000; // Default to 2s (Healthy state)
          static int global_cycle_count = 0;             // Increments every full loop

          // -----------------------------------------------------------------------
          // STEP 1: DYNAMIC TIMING CALCULATION
          // -----------------------------------------------------------------------
          // The cycle duration is adaptive. It expands to fit the longest active
          // fault code in the system, preventing long dead-air waits for short codes.
          
          uint32_t now = millis();
          int32_t time_into_cycle = now - cycle_start_ms;

          // Check if the current cycle has completed
          if (time_into_cycle >= current_cycle_duration || time_into_cycle < 0) {
              // Start new cycle
              cycle_start_ms = now;
              time_into_cycle = 0;
              global_cycle_count++;

              // Scan global registry to find the highest active Category ID
              int max_active_category = -1;
              for (int cat = 0; cat < 16; cat++) {
                  auto &faults = id(global_instance_faults)[cat];
                  for (bool f : faults) {
                      if (f) {
                          if (cat > max_active_category) max_active_category = cat;
                          break; // Found a fault in this category, move to next
                      }
                  }
              }

              // Calculate required duration for the next cycle
              if (max_active_category == -1) {
                  // System Healthy: Default to 2s (1s ON, 1s OFF)
                  current_cycle_duration = 2000;
              } else {
                  // System Faulted: Calculate exact time needed for the longest code
                  int pips = max_active_category + 1;
                  
                  // Calculate total time for pips
                  uint32_t total_pip_time = pips * PIP_DURATION_MS;
                  
                  // Calculate total time for group gaps (1 gap after every 4 pips)
                  // Integer division ensures gap is only added for full groups of 4
                  int gaps = (pips - 1) / 4;
                  uint32_t total_gap_time = gaps * GROUP_GAP_MS;

                  current_cycle_duration = HEADER_MS + PRE_PIP_GAP_MS + total_pip_time + total_gap_time + END_PADDING_MS;
                  
                  // Enforce minimum 2s to allow the Green/Blue header to finish properly
                  if (current_cycle_duration < 2000) current_cycle_duration = 2000;
              }
          }

          // -----------------------------------------------------------------------
          // STEP 2: REGISTRY MAPPING
          // -----------------------------------------------------------------------
          // Invert the Category->LED registry to build a list of assignments per LED.
          // This allows each LED to know exactly which Categories/Instances it monitors.
          
          std::map<esphome::light::LightState*, std::vector<std::pair<int, int>>> assignments;
          
          for (int cat = 0; cat < 16; cat++) {
             auto &leds_in_cat = id(global_led_registry)[cat];
             for (size_t inst = 0; inst < leds_in_cat.size(); inst++) {
                 auto *led = leds_in_cat[inst];
                 if (led != nullptr) assignments[led].push_back({cat, (int)inst});
             }
          }

          // -----------------------------------------------------------------------
          // STEP 3: RENDER
          // -----------------------------------------------------------------------
          // "Spotlight Logic": The Healthy Green Pulse is only active during the Header phase.
          // This ensures the rest of the cycle is dark, making Red Pips easier to count.
          bool is_header_phase = (time_into_cycle < HEADER_MS);

          for (auto const& [led, assigned_list] : assignments) {
              
              // Filter assigned items to find currently active faults
              std::vector<int> active_fault_categories;
              for (auto &pair : assigned_list) {
                  int cat = pair.first;
                  int inst = pair.second;
                  auto &cat_faults = id(global_instance_faults)[cat];
                  // Check if this specific instance index is flagged as true
                  if (inst < cat_faults.size() && cat_faults[inst]) {
                      active_fault_categories.push_back(cat);
                  }
              }

              LedStateContext &ctx = states[led];
              float bri = 0.5;
              auto call = led->make_call();

              // CASE A: UNASSIGNED LED
              // Force off to prevent floating states
              if (assigned_list.empty()) {
                  call.set_state(false).perform();
                  continue;
              }

              // CASE B: HEALTHY LED
              // No active faults found in assigned categories
              if (active_fault_categories.empty()) {
                  ctx.fault_index = 0; // Reset index for future faults
                  
                  if (is_header_phase) {
                      // Pulse Green during the global sync header
                      if (${board_has_rgb}) call.set_rgb(0.0, 1.0, 0.0);
                      call.set_brightness(bri).set_state(true);
                  } else {
                      // Stay dark during the data phase to avoid visual noise
                      call.set_state(false);
                  }
                  call.perform();
                  continue;
              }

              // CASE C: FAULTED LED
              
              // Handle Multi-Fault Rotation:
              // If this LED has multiple faults, switch to the next one 
              // only when the global cycle restarts.
              if (ctx.last_cycle_id != global_cycle_count) {
                  ctx.last_cycle_id = global_cycle_count;
                  ctx.fault_index++;
                  // Wrap around if index exceeds number of active faults
                  if (ctx.fault_index >= active_fault_categories.size()) ctx.fault_index = 0;
              }

              // Retrieve the specific category to display for this cycle
              int current_cat = active_fault_categories[ctx.fault_index];
              int pips_needed = current_cat + 1; // Cat 0 = 1 pip

              // --- RENDERING PHASES ---

              // Phase 1: Blue Header (Syncs with Healthy Green)
              if (time_into_cycle < HEADER_MS) {
                  if (${board_has_rgb}) call.set_rgb(0.0, 0.0, 1.0);
                  call.set_brightness(bri).set_state(true);
                  call.perform();
                  continue;
              }

              // Phase 2: Gap (Silence before pips start)
              uint32_t start_pips = HEADER_MS + PRE_PIP_GAP_MS;
              if (time_into_cycle < start_pips) {
                  call.set_state(false).perform();
                  continue;
              }

              // Phase 3: Grouped Pips
              uint32_t t_pips = time_into_cycle - start_pips;
              
              // Calculate Time Block logic for grouping (4 pips + 1 gap)
              // Block Duration = (4 * 300ms) + 500ms = 1700ms
              const uint32_t BLOCK_DURATION = (4 * PIP_DURATION_MS) + GROUP_GAP_MS;
              
              int block_idx = t_pips / BLOCK_DURATION;
              uint32_t t_within_block = t_pips % BLOCK_DURATION;
              
              // Calculate how many pips were displayed in previous full blocks
              int pips_rendered_previously = block_idx * 4;
              
              // Check if we are in the "Blinking" part of the block or the "Gap" part
              if (t_within_block < (4 * PIP_DURATION_MS)) {
                  // Inside the blinking window
                  int pip_in_block = t_within_block / PIP_DURATION_MS; // 0..3
                  int actual_pip_number = pips_rendered_previously + pip_in_block + 1; // 1-based index
                  
                  if (actual_pip_number <= pips_needed) {
                      // We are within the count for this fault code.
                      // Toggle ON/OFF based on 50% duty cycle of PIP_DURATION_MS
                      if ((t_within_block % PIP_DURATION_MS) < (PIP_DURATION_MS / 2)) {
                           // LED ON (Red)
                           if (${board_has_rgb}) call.set_rgb(1.0, 0.0, 0.0);
                           call.set_brightness(bri).set_state(true);
                      } else {
                           // LED OFF (Inter-pip pause)
                           call.set_state(false);
                      }
                  } else {
                      // Count exceeded, stay dark
                      call.set_state(false);
                  }
              } else {
                  // We are in the Inter-Group Gap (the pause after 4 pips)
                  call.set_state(false);
              }
              call.perform();
          }



  # LED Assignment Report in logs, enabled via enable_led_logging substitution
  - interval: 60s
    then:
      - lambda: |-
          // If the substitution is false, stop
          if (!${enable_led_logging}) return;

          ESP_LOGI("led_rpt", "┌──────────────────────────────┐");
          ESP_LOGI("led_rpt", "│    LED REGISTRY ASSIGNMENT   │");
          ESP_LOGI("led_rpt", "└──────────────────────────────┘");

          bool registry_empty = true;

          for (int cat = 0; cat < 16; cat++) {
            // Access the LED Registry
            auto &leds = id(global_led_registry)[cat];
            
            // Skip empty categories
            if (leds.empty()) continue;
            registry_empty = false;

            // Translate ID to Name
            std::string cat_name;
            switch(cat) {
                case 0: cat_name = "API / MQTT "; break;
                case 1: cat_name = "BMS        "; break;
                case 2: cat_name = "CAN->INV   "; break;
                case 3: cat_name = "RS485->INV "; break;
                case 4: cat_name = "SHUNT      "; break;
                case 5: cat_name = "BALANCER   "; break;
                case 6: cat_name = "NETWORK    "; break;
                case 7: cat_name = "AUX 1      "; break;
                default: cat_name = "CAT_" + to_string(cat) + "     "; break;
            }

            // Build the status string for this category's LEDs
            std::string status_line = "";
            
            for (size_t i = 0; i < leds.size(); i++) {
                // Check if the pointer is valid
                if (leds[i] != nullptr) {
                    status_line += "[LINK] ";
                } else {
                    status_line += "[NULL] ";
                }
            }

            ESP_LOGI("led_rpt", "   %s: %s", cat_name.c_str(), status_line.c_str());
          }

          if (registry_empty) {
             ESP_LOGW("led_rpt", ">> WARNING: NO LEDS REGISTERED");
          }
          ESP_LOGI("led_rpt", "--------------------------------");
