# Updated  : 2026.06.28
# Version  : 1.1.3
# GitHub   : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# +--------------------------------------------------------------------------+
# | 1280x720 LVGL Display for YamBMS Node (Tab5 design)
# +--------------------------------------------------------------------------+
# | Import this package on the YamBMS node to enable the integrated display.
# | Reads data directly from local ESPHome YamBMS sensors.
# |
# | Required substitutions: `yambms_id` - the YamBMS instance ID.
# |
# +--------------------------------------------------------------------------+

packages:
  display_lvgl:    !include board_options_display_lvgl_design_1280x720_Tab5.yaml
  display_sensors: !include board_options_display_lvgl_esphome_sensors_Tab5.yaml
