# Updated : 2026.08.27
# Version : 1.1.0
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# LED DevKitC-1 V1.0 = 48 / V1.1 = 38

substitutions:
  # canbus_esp32_can
  tx_pin_4: '38'
  rx_pin_4: '39'
  # RGB LED
  rgb_led_pin: '48' 

packages:
  pvbrain2: !include board_ESP32-S3_DevKitC-1_PVbrain2.yaml
