# Updated : 2026.01.14
# Version : 1.1.3
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

# https://wiki.lilygo.cc/get_started/en/High_speed/T-Connect-Pro/T-Connect-Pro.html

substitutions:
  board_chip: "ESP32-S3"
  board_name: "LilyGo T-Connect Pro"
  # Interfaces GPIOs
  # uart_esp_1: RS232
  tx_pin_1: '4'
  rx_pin_1: '5'
  # uart_esp_2: RS485
  tx_pin_2: '17'
  rx_pin_2: '18'
  # canbus_esp32_can: CAN
  tx_pin_4: '6'
  rx_pin_4: '7'

  lilygo_led_1: '46'
  lilygo_led_2: '3'
  lilygo_led_3: '21'
  lilygo_led_4: '41'

  lilygo_btn_a: '39'
  lilygo_btn_b: '40'

  lilygo_rly: '8'

packages:
  device_base: !include ../base/device_base.yaml
  device_base_ethernet: !include ../base/device_base_ethernet.yaml
  board_rgb_led: !include board_options_rgb_leds_status.yaml

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB # ajust according to your ESP32-S3 version
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio             # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing

#wifi:
#  id: my_network
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
#  domain: !secret domain
#  reboot_timeout: 0s

# ESPHome does not support W5500 and other SPI devices at the same SPI bus:
# https://github.com/esphome/esphome/discussions/6720
ethernet:
  id: my_network
  type: W5500
  clk_pin: 12
  mosi_pin: 11
  miso_pin: 13
  cs_pin: 10
  interrupt_pin: 9
  reset_pin: 48
  clock_speed: 40MHz

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"

output:
# ESP32 board without LED
  - platform: template
    id: esp_output
    type: binary
    write_action:
      - lambda: |-
          if (id(${canbus_id}_status).state == true) {
            if(state == false) {
              id(esp_light_2).turn_on().set_brightness(0.2).set_rgb(0.0, 0.0, 1.0).perform();
            } else {
              id(esp_light_2).turn_on().set_brightness(0.5).set_rgb(0.0, 0.0, 1.0).perform();
            }
          } else {
            id(esp_light_2).turn_on().set_brightness(0.5).set_rgb(1.0, 0.0, 0.0).perform();
          }

light:

  - platform: binary
    id: esp_light
    output: esp_output

  # RGB LED for API Status
  - platform: esp32_rmt_led_strip
    id: esp_light_1
    rgb_order: GRB
    pin: ${lilygo_led_1}
    num_leds: 1
    chipset: ws2812
    rmt_symbols: 48
    restore_mode: ALWAYS_OFF
    default_transition_length: 0.2s
  # RGB LED for CAN/Inverter Status
  - platform: esp32_rmt_led_strip
    id: esp_light_2
    rgb_order: GRB
    pin: ${lilygo_led_2}
    num_leds: 1
    chipset: ws2812
    rmt_symbols: 48
    restore_mode: ALWAYS_OFF
    default_transition_length: 0.2s
  # RGB LED for BMS Status
  - platform: esp32_rmt_led_strip
    id: esp_light_3
    rgb_order: GRB
    pin: ${lilygo_led_3}
    num_leds: 1
    chipset: ws2812
    rmt_symbols: 48
    restore_mode: ALWAYS_OFF
    default_transition_length: 0.2s
  # RGB LED for SoC
  - platform: esp32_rmt_led_strip
    id: esp_light_4
    rgb_order: GRB
    pin: ${lilygo_led_4}
    num_leds: 1
    chipset: ws2812
    rmt_symbols: 48
    restore_mode: ALWAYS_OFF
    default_transition_length: 0.2s

# Relay: IO8
switch:
  - platform: gpio
    name: "Relay"
    icon: "mdi:electric-switch"
    pin:
      number: ${lilygo_rly}
      inverted: true
      mode: OUTPUT_OPEN_DRAIN
    restore_mode: RESTORE_DEFAULT_OFF

# LED 1 - API
# - Green Connected, Red not connected
# LED 2 - CAN
# - Green Connected, Blue for traffic, Red not connected
# LED 3 - BMS Status
# - 100% batteries online = Green, 0% = Red, anythingelse = Yellow
# LED 4 - SOC
# - 100-75 Green, 75-50 Yellow, 50-25 Orange, 25-0 Red
interval:    
  - interval: 1s
    then:
      - lambda: |-
          auto call = id(esp_light_1).turn_on();
          call.set_brightness(0.5);
          if (id(esp32_online_status).state) {
            call.set_rgb(0.0, 1.0, 0.0); // Green #00FF00
          } else {
            call.set_rgb(1.0, 0.0, 0.0); // Red #FF0000
          }
          call.perform();
  - interval: 1s
    then:
      - lambda: |-
          if (id(${canbus_id}_status).state == false) {
            id(esp_light_2).turn_on().set_brightness(0.5).set_rgb(1.0, 0.0, 0.0).perform();
          }  
  - interval: 10s
    then:
      - lambda: |-
          auto call = id(esp_light_3).turn_on();
          call.set_brightness(0.5);
          if (id(${yambms_id}_bms_combined).state == 0) {
            call.set_rgb(1.0, 0.0, 0.0); // Red #FF0000
          } else if (id(${yambms_id}_bms_count).state ==id(${yambms_id}_bms_combined).state) {
            call.set_rgb(0.0, 1.0, 0.0); // Green #00FF00
          } else {
            call.set_rgb(1.0, 1.0, 0.0); // Yellow #FFFF00
          }
          call.perform();                    
  - interval: 5s
    then:
      - lambda: |-
          if(id(${yambms_id}_var_total_installed_battery_capacity) > 0) {
            auto call = id(esp_light_4).make_call();
            call.set_brightness(0.5);
            if (id(${yambms_id}_battery_soc).state >= 75) 
              call.set_rgb(0.0, 1.0, 0.0); // Green #00FF00
            else if (id(${yambms_id}_battery_soc).state >=50) 
              call.set_rgb(1.0, 1.0, 0.0); // Yellow #FFFF00:q
            else if (id(${yambms_id}_battery_soc).state >=25 ) 
              call.set_rgb(1.0, 0.65, 0.0);  // Orange #FFA500
            else
              call.set_rgb(1.0, 0.0 , 0.0);  // Red #FF0000
            call.perform();
          } else {
            id(esp_light_4).turn_on().set_brightness(0.5).set_rgb(0.0, 0.0 , 1.0).perform();
          }