# Updated : 2025.12.23
# Version : 1.0.2
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# TCP Multi-Node Server 2 Example
# See TCP_example_multi-node_YamBMS_server_1.yaml for detailed comments

substitutions:
  friendly_name: 'YamBMS TCP Server 2'
  hostname: !secret server2_hostname
  name: !secret server2_hostname
  bms_id: '2' # Different from Server 1

esphome:
  name: ${hostname}
  friendly_name: ${friendly_name}

packages:
  board_base: !include ../../packages/base/device_base.yaml
  board_wifi: !include ../../packages/base/device_base_wifi.yaml

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  enable_ipv6: true
  manual_ip:
    static_ip: !secret server2_ip  # Different from Server 1
    gateway: !secret gateway_ipv4
    subnet: !secret subnet_ipv4
    dns1: !secret dns1_ipv4
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

mdns:
  disabled: false
  services:
    - service: modbus-tcp
      protocol: tcp
      port: 502
      txt:
        bms_id: "2"
        role: "server"

logger:
  level: INFO

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

packages:
  bms2_tcp: !include
    file: ../../packages/bms/bms_modbus_tcp_server.yaml
    vars:
      bms_id: '2'
      modbus_uart_id: 'uart_esp_1'
      modbus_role: 'server'

  bms2: !include
    file: ../../packages/bms/bms_JK_UART.yaml
    vars:
      bms_id: '2'
      bms_name: 'JK-BMS 2'
      bms_uart_id: 'uart_esp_2'
      bms_cell_max_cycles: '6000.0'

uart:
  - id: uart_esp_1
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 19200
  - id: uart_esp_2
    tx_pin: GPIO14
    rx_pin: GPIO12
    baud_rate: 115200

text_sensor:
  - platform: template
    name: "${friendly_name} Access URLs"
    icon: "mdi:link-variant"
    entity_category: diagnostic
    lambda: |-
      std::string urls = "";
      if (id(my_network).is_connected()) {
        urls += "IPv4: " + id(my_network).get_ip_address().str() + ":502\n";
      }
      #ifdef USE_NETWORK_IPV6
        auto ipv6 = id(my_network).get_ipv6();
        if (ipv6.size() > 0) {
          urls += "IPv6: [" + ipv6[0].str() + "]:502\n";
        }
      #endif
      urls += "mDNS: " + std::string("${hostname}") + ".local:502";
      return urls;
