# Updated : 2025.12.23
# Version : 1.0.2
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# +--------------------------------------+
# | TCP Multi-Node Client Example        |
# +--------------------------------------+
#
# PURPOSE:
#   Master node that polls BMS servers over network
#   Combines data and controls inverter
#
# IMPORTANT:
#   Requires hardware TCP-to-Modbus bridge ($30-100)
#   ESPHome doesn't have native Modbus TCP client yet
#
# ARCHITECTURE:
#   ESP32 → Modbus RTU → Hardware Bridge → Network → TCP Servers
#
# BRIDGE PRODUCTS:
#   - EBYTE NT1 (~$40)
#   - USR-TCP232-410S (~$30)
#   - Elfin-EE11 (~$50)
#
# NOTE ON mDNS:
#   Hardware bridges typically don't support mDNS hostname resolution
#   Use static IPs for server configuration in the bridge
#   ESP32 can still use mDNS for its own hostname
#
# SEE ALSO:
#   - secrets.yaml.example (network configuration)
#   - Package: packages/bms/bms_modbus_tcp_client.yaml
#   - Docs: documents/README/YamBMS_multi-node_TCP_modbus_solution.md
#   - MQTT Alternative: YamBMS_MQTT_vs_ModbusTCP_analysis.md (supports mDNS!)

substitutions:
  friendly_name: 'YamBMS TCP Client'
  hostname: !secret client_hostname
  name: !secret client_hostname
  yambms_id: 'yambms'

esphome:
  name: ${hostname}
  friendly_name: ${friendly_name}

packages:
  board_base: !include ../../packages/base/device_base.yaml
  board_wifi: !include ../../packages/base/device_base_wifi.yaml

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Client network configuration
wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  enable_ipv6: true
  manual_ip:
    static_ip: !secret client_ip
    gateway: !secret gateway_ipv4
    subnet: !secret subnet_ipv4
    dns1: !secret dns1_ipv4
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

mdns:
  disabled: false

logger:
  level: INFO

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

# Modbus Client (connects to local bridge, NOT directly to servers)
packages:
  modbus_itf: !include
    file: ../../packages/board/board_options_itf_modbus.yaml
    vars:
      modbus_role: 'client'
      modbus_uart_id: 'uart_esp_1'
      modbus_baud_rate: '19200'
      modbus_update_interval: '5s'

  # BMS Server 1
  # Hardware bridge forwards Modbus address 1 to server1_ip:502
  bms1: !include
    file: ../../packages/bms/bms_combine_modbus_client.yaml
    vars:
      bms_id: '1'
      bms_name: 'BMS 1'
      bms_model: 'YamBMS'
      bms_protocol: 'Modbus TCP'

  # BMS Server 2
  # Hardware bridge forwards Modbus address 2 to server2_ip:502
  bms2: !include
    file: ../../packages/bms/bms_combine_modbus_client.yaml
    vars:
      bms_id: '2'
      bms_name: 'BMS 2'
      bms_model: 'YamBMS'
      bms_protocol: 'Modbus TCP'

  # Main YamBMS logic
  yambms: !include ../../packages/yambms.yaml

  # CAN to inverter
  canbus: !include
    file: ../../packages/board/board_options_itf_canbus_esp32_can.yaml
    vars:
      canbus_node_id: 'canbus_1'

  inverter: !include
    file: ../../packages/inverter/protocol_PYLON_CAN.yaml
    vars:
      inverter_node_id: 'inverter_1'
      inverter_canbus_id: 'canbus_1'

# UART: Connects to hardware bridge
uart:
  - id: uart_esp_1
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 19200

# +--------------------------------------+
# | Hardware Bridge Configuration        |
# +--------------------------------------+
#
# BRIDGE SETUP:
#   Configure your hardware bridge to map Modbus addresses to server IPs:
#
#   From secrets.yaml:
#     Modbus Addr 1 → !secret server1_ip:502  (e.g., 192.168.1.101:502)
#     Modbus Addr 2 → !secret server2_ip:502  (e.g., 192.168.1.102:502)
#     Modbus Addr 3 → !secret server3_ip:502  (e.g., 192.168.1.103:502)
#
#   IMPORTANT: Most hardware bridges require IP addresses, NOT hostnames
#   Use static IPs from secrets.yaml (server1_ip, server2_ip, etc.)
#
# WIRING:
#   ESP32 TX (GPIO17) → Bridge RX
#   ESP32 RX (GPIO16) → Bridge TX
#   ESP32 GND → Bridge GND
#
# BRIDGE SETTINGS:
#   - Mode: Modbus TCP Client
#   - Local: RS485/RTU (19200 baud)
#   - Remote: TCP (port 502)
#
# HOW IT WORKS:
#   1. ESP32 polls "Address 1" via Modbus RTU
#   2. Bridge translates to TCP and connects to server1_ip:502
#   3. Server responds via TCP
#   4. Bridge translates back to Modbus RTU
#   5. ESP32 receives response
#
# TESTING:
#   1. Verify servers reachable:
#      ping !secret server1_ip
#      ping !secret server2_ip
#
#   2. Test server ports:
#      nc -zv $(cat secrets.yaml | grep server1_ip | cut -d: -f2) 502
#
#   3. Check bridge can connect to servers
#   4. Monitor ESP32 logs for BMS data
#
# +--------------------------------------+
# | Alternative: MQTT (Recommended)      |
# +--------------------------------------+
#
# MQTT supports mDNS natively - no hardware bridge needed!
#
# Advantages:
#   - No hardware bridge ($0 vs $30-100)
#   - Native mDNS support (use server1.local)
#   - Native IPv6 support
#   - More efficient (push vs poll)
#   - Better security (auth, TLS)
#
# See: documents/README/YamBMS_MQTT_vs_ModbusTCP_analysis.md
