# Updated : 2025.12.23
# Version : 1.0.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# +--------------------------------------+
# | TCP Multi-Node Server Example        |
# +--------------------------------------+
#
# PURPOSE:
#   BMS server node that exposes data over network
#   Eliminates RS485 bus wiring between nodes
#
# WHAT THIS DOES:
#   - Monitors 1-3 local BMS units (via UART)
#   - Exposes all BMS data on TCP port 502
#   - Master node reads data over WiFi/Ethernet
#
# REQUIREMENTS:
#   - Network (WiFi or Ethernet)
#   - Unique bms_id per server
#   - Static IP recommended
#
# SEE ALSO:
#   - Full documentation: documents/README/YamBMS_multi-node_TCP_modbus_solution.md
#   - Package details: packages/bms/bms_modbus_tcp_server.yaml

substitutions:
  friendly_name: 'YamBMS TCP Server 1'
  hostname: 'yambms-tcp-server-1'
  name: 'yambms-tcp-server-1'
  bms_id: '1' # Unique Modbus address (1-255)

esphome:
  name: ${hostname}
  friendly_name: ${friendly_name}

# Base packages
packages:
  board_base: !include ../../packages/base/device_base.yaml
  board_wifi: !include ../../packages/base/device_base_wifi.yaml

# Board configuration
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Network - WiFi
wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.101  # Change for each server
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Alternative: Ethernet (uncomment for Ethernet boards)
# ethernet:
#   id: my_network
#   type: LAN8720
#   mdc_pin: GPIO23
#   mdio_pin: GPIO18
#   clk_mode: GPIO0_IN
#   phy_addr: 1
#   power_pin: GPIO16
#   manual_ip:
#     static_ip: 192.168.1.101
#     gateway: 192.168.1.1
#     subnet: 255.255.255.0

logger:
  level: INFO

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

# TCP Server: Exposes BMS data on port 502
packages:
  bms1_tcp: !include
    file: ../../packages/bms/bms_modbus_tcp_server.yaml
    vars:
      bms_id: '1'
      modbus_uart_id: 'uart_esp_1'
      modbus_role: 'server'

  # Local BMS monitoring (choose your BMS type)
  bms1: !include
    file: ../../packages/bms/bms_JK_UART.yaml
    vars:
      bms_id: '1'
      bms_name: 'JK-BMS 1'
      bms_uart_id: 'uart_esp_2'
      bms_cell_max_cycles: '6000.0'

  # Optional: Add second BMS
  # bms2: !include
  #   file: ../../packages/bms/bms_Daly_UART.yaml
  #   vars:
  #     bms_id: '1'  # Same node, different BMS
  #     bms_name: 'Daly BMS 2'
  #     bms_uart_id: 'uart_esp_3'

# UART configuration (adjust pins for your board)
uart:
  - id: uart_esp_1  # Internal: used by TCP bridge
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 19200
  - id: uart_esp_2  # BMS connection
    tx_pin: GPIO14
    rx_pin: GPIO12
    baud_rate: 115200

# +--------------------------------------+
# | Quick Start                          |
# +--------------------------------------+
#
# 1. Configure WiFi in secrets.yaml
# 2. Set unique static_ip (101, 102, 103...)
# 3. Set unique bms_id ('1', '2', '3'...)
# 4. Configure BMS package (JK, Daly, etc.)
# 5. Set UART pins for your board
# 6. Flash: esphome run this-file.yaml
# 7. Check IP address in logs
# 8. Test: nc -zv <ip> 502
#
# MONITORING:
#   - "TCP Bridge Active" sensor
#   - "WiFi Signal" sensor
#   - "IP Address" text sensor
#
# DATA EXPOSED:
#   All 33+ BMS registers on <ip>:502
#   Master node polls via network
