# Updated : 2026.01.30
# Version : 1.2.8
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  # +--------------------------------------+
  # | Use the settings below with caution  |
  # +--------------------------------------+
  # Auto charge current control will automatically reduce the charging current as a cell reaches the BMS "cell_voltage_overvoltage_protection" value.
  # Tapering will begin once the maximum cell voltage exceeds float voltage.
  # If unsure, leave the below settings as default, this will ensure charge current will taper correctly.
  # Factor to control the end of the charge current curve. A setting below 2 will extend the curve, above 2 will shorten the curve.
  charge_a_factor_curve_end: '2.0'
  # Factor to adjust the shape of the charge current curve.
  # A setting above 1 will reduce current at a slow rate after the float voltage is reached, then increase as a cell approaches the BMS "cell_voltage_overvoltage_protection" value.
  # A factor below 1 will reduce current at a fast rate after the float voltage is reached, then slow as a cell approaches the BMS "cell_voltage_overvoltage_protection" value.
  charge_a_factor_curve_shape: '1.8'
  # Linear charge current taper
  # Begins tapering 2V before bulk voltage target
  # CCL reduces linearly: full current at (target - 2V), zero at target
  charge_taper_start_offset: '2.0'  # Voltage before target to start taper
  
switch:
  - platform: template
    name: ${name} ${yambms_name} Automatic Charge Current
    id: ${yambms_id}_switch_auto_ccl
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    entity_category: config

sensor:
  # +--------------------------------------+
  # | Auto Charge Current Limit            |
  # +--------------------------------------+
  # Calculate charge current reduction based on proximity to bulk voltage target.
  # Implements linear taper: full current until 2V below target, then proportional reduction to zero at target voltage.
  - platform: copy
    source_id: ${yambms_id}_max_cell_voltage
    name: ${name} ${yambms_name} Initial Charge Current
    id: auto_ccl_initial
    unit_of_measurement: A
    device_class: current
    internal: true
    filters:
    - lambda: |-
        // Variables
        double max_charge_a = id(${yambms_id}_max_charge_current).state;
        double target_voltage = id(${yambms_id}_bulk_voltage).state;
        double current_voltage = id(${yambms_id}_total_voltage).state;
        
        // Auto Charge Current function
        if (!id(${yambms_id}_switch_auto_ccl).state) {
          // No change to charge current required
          return 0.0;
        }
        
        // Linear taper algorithm
        double taper_start_voltage = target_voltage - 2.0;  // Start taper 2V before target
        
        if (current_voltage < taper_start_voltage) {
          // Full current until 2V away from target
          return 0.0;  // No reduction
        }
        
        // Calculate proportional taper
        double voltage_error = target_voltage - current_voltage;
        double taper_range = 2.0;
        
        // CCL reduction proportional to how close we are to target
        double ccl_multiplier = voltage_error / taper_range;
        ccl_multiplier = max(0.0, min(1.0, ccl_multiplier));  // Clamp between 0 and 1
        
        // Return the delta (negative value reduces CCL)
        return (ccl_multiplier * max_charge_a) - max_charge_a;
        
  # Second, an exponential moving average is calculated. This will be used to smooth the transition between different initial charge current values.
  - platform: copy
    source_id: auto_ccl_initial
    name: ${name} ${yambms_name} Moving Average Charge Current
    id:  auto_ccl_moving_average
    unit_of_measurement: A
    device_class: current
    internal: true
    filters:
    - exponential_moving_average:
        alpha: 0.15
        send_every: 1
        send_first_at: 1

  # Third, if the instantaneous initial charge current value is lower than the moving average, use that, otherwise use the moving average.
  # This means that cell voltage spikes will be reacted to quickly, but reduced cell voltages will not, preventing oscillation of requested current.
  - platform: copy
    source_id: auto_ccl_initial
    name: ${name} ${yambms_name} Auto Charge Current
    id: auto_ccl
    unit_of_measurement: A
    device_class: current
    accuracy_decimals: 1
    internal: true
    filters:
    - lambda: |-
        // Variables
        double auto_ccl = round((min(id(auto_ccl_moving_average).state, x) * 10) / 10);

        id(${yambms_id}_var_auto_ccl) = auto_ccl;
        return auto_ccl;
